// Idea bank: article. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
// Strings use double quotes so apostrophes read naturally; the text itself never contains quotation marks.
export default [
  // ── spark ───────────────────────────────────────────────────────────────────
  ['spark', "A piece that explains {topic} entirely through the ordinary objects that give the whole thing away, each handled like evidence at a hearing."],
  ['spark', "An article about the job nobody outside the field knows exists, the one that quietly stops the visible work from falling apart."],
  ['spark', "A how-to for a skill you are still bad at, where the failures are the useful part and the expert advice only makes cameos."],
  ['spark', "One ordinary afternoon reported through three people with very different stakes, with the real argument hiding in what each of them leaves out."],
  ['spark', "A piece that takes the dullest question inside {topic} and gives it the seriousness of a mystery."],
  ['spark', "A guide for someone who will use the advice exactly once, at the worst possible moment, and needs it to work with no background at all."],
  ['spark', "An affectionate audit of a ritual everyone in a field performs and nobody has ever asked the newest member to justify."],
  ['spark', "A history told backward, from a mundane habit to the strange little decision that made it normal."],
  ['spark', "A piece built around the one question people are quietly embarrassed to ask about {topic}, chased all the way to a real answer."],
  ['spark', "An article addressed to whoever inherits the problem a generation from now, explaining what today's people got right by accident and wrong on purpose."],
  ['spark', "A comparison of two things that look like rivals but turn out to be the same process seen from opposite ends."],
  ['spark', "A piece in which {theme} never gets named but explains every odd choice people make around {topic}."],

  // ── angle ───────────────────────────────────────────────────────────────────
  ['angle', "The view from the people who do the quiet daily work behind {topic}, rather than from the people who speak about it in public."],
  ['angle', "Follow the money, but gently: not who profits, but who quietly pays the small recurring cost nobody has ever added up."],
  ['angle', "The near miss as an angle: the time something almost went wrong, and what the almost reveals that a clean success never would."],
  ['angle', "Seeing {topic} as a negotiation between two groups who each sincerely believe they are the reasonable ones."],
  ['angle', "A history of the word itself: how the term people use for this subject changed meaning, and what each shift let them stop noticing."],
  ['angle', "The beginner's mistake as an angle: what the standard first error teaches that the polished expert version quietly hides."],
  ['angle', "The cost of the accepted fix: the problem gets the attention, so look instead at what the popular solution takes from people who never agreed to pay."],
  ['angle', "One small place, a single workshop, street or office, treated as a working model of the larger question, with the big picture earning its place afterward."],
  ['angle', "The shape of {topic} across one person's whole life, instead of in a single frozen moment."],
  ['angle', "The exception as an angle: the one person or place that ought to follow the pattern and refuses, whose reasons expose the pattern's hidden assumptions."],
  ['angle', "An angle of regret: ask people who made the standard choice long ago what they would tell their earlier selves, and listen for the answer that repeats."],
  ['angle', "The scale flip: the kitchen-table version of a story usually told in institutional terms, or the institutional version of one usually told at the kitchen table."],
  ['angle', "An angle that asks what {theme} has to do with {topic}, since the odd pairing may turn out to be the whole piece."],

  // ── hook ────────────────────────────────────────────────────────────────────
  ['hook', "An opening built around the moment an insider first realised the usual explanation was wrong, with the evidence arriving slowly and the reader suspecting first."],
  ['hook', "A tiny, specific failure, a missed bus, a wrong form, a ruined batch, that widens until it is plainly about {topic}."],
  ['hook', "A hook that begins with the writer admitting a belief the reporting later took apart, so the reader enters as a fellow sceptic rather than a student."],
  ['hook', "A rule everyone follows without knowing who made it, with the promise that the piece will trace it back to an actual person."],
  ['hook', "A puzzle hook: two facts that cannot both be true as they stand, set side by side, with a promise to reconcile them."],
  ['hook', "A hook that names the small private doubt readers have about {topic} and rarely say aloud, so they feel seen before they feel informed."],
  ['hook', "Starting in the middle of an argument between two people who both have a point, with the article as the thing that eventually referees it."],
  ['hook', "A hook from absence: begin with what is conspicuously missing, a silent room, an empty shelf, a form with no complaints, and make the reader want the reason."],
  ['hook', "A quiet-stakes opening: a small decision the reader will face this week, followed by the slow reveal of how much quietly hangs on it."],
  ['hook', "The last ordinary minute before something changed, held still long enough for the reader to spot what everyone at the time missed."],
  ['hook', "A hook that flips authority by leading with the most junior or least credentialled voice in the story and promising the experts will have to answer them."],
  ['hook', "An unfashionable claim about {topic} stated plainly at the top, which the rest of the piece must earn the right to keep."],

  // ── headline ────────────────────────────────────────────────────────────────
  ['headline', "A headline direction that promises a verdict and withholds the reasoning, so the click comes from wanting to see the argument rather than the answer."],
  ['headline', "A headline built from two ordinary words that should not share a sentence, so the reader needs the piece itself to reconcile them."],
  ['headline', "A plain, literal headline over a surprising piece, where the calm tone lets the content do all the startling."],
  ['headline', "A question headline, but only if the article honestly answers it by the end and the answer is more interesting than a simple no."],
  ['headline', "A headline that names the reader's specific worry in their own vocabulary rather than the industry's."],
  ['headline', "A headline that borrows the rhythm of a proverb or house rule and bends it just enough to point at {topic}."],
  ['headline', "A headline that sets a gain against a quiet loss, the thing won and the thing given up, and leaves the reader to weigh them."],
  ['headline', "Two headline directions to test on a friend: one promising a result, one promising a mystery, then notice which you would feel honest putting on the finished piece."],
  ['headline', "A headline that leads with the unexpected person or object rather than the subject, saving the connection for the subhead."],
  ['headline', "A deliberately small headline for a large subject, narrowing to one street, one tool or one afternoon, so the scale itself is the intrigue."],
  ['headline', "A headline that states the conclusion as a calm, almost boring fact, since the surprise lives in why it is true."],
  ['headline', "A headline whose urgency comes from the argument rather than from the volume, with a time pressure the piece can actually justify."],

  // ── structure ───────────────────────────────────────────────────────────────
  ['structure', "The conclusion up front, then the rest of the piece spent on the three strongest reasons to doubt it, ending on whether it survives."],
  ['structure', "Frame and return: one small scene at the start, a long departure into the argument, then back to the scene so it now means something different."],
  ['structure', "A piece organised as a trial, with sections for the case for, the case against, the witness nobody called, and a verdict the writer is willing to reverse."],
  ['structure', "Reverse chronology that begins with the outcome and peels back one decision at a time until the reader meets the first, innocent choice."],
  ['structure', "Each section closes on the objection the next section has to answer, so the argument moves like a conversation with a polite sceptic."],
  ['structure', "Section headings that are the questions a reader would actually ask, in the order they would ask them, so the whole piece reads as a patient answer."],
  ['structure', "A zoom structure: one household or room, then the street, then the system, then back into the room so the last image carries the full weight."],
  ['structure', "Two timelines braided together, the official version and the lived version, converging only in the final section."],
  ['structure', "A clean first half that states the accepted story and a second half that quietly dismantles it, with the hinge placed exactly in the middle."],
  ['structure', "A ladder of increasingly uncomfortable questions, each answered before the reader is allowed to climb to the next."],
  ['structure', "A long central section framed by brief interludes from affected people, each one a short burst that works like a chorus."],
  ['structure', "An alternating rhythm of how and why, where every practical step is followed by the reason a sceptic might refuse to take it."],

  // ── sources ─────────────────────────────────────────────────────────────────
  ['sources', "Look for the person who used to do this job and left, since former insiders can explain the unwritten rules the current ones no longer notice."],
  ['sources', "Find whoever writes the manual, the training notes or the checklist, and ask what they had to leave out."],
  ['sources', "For {topic}, seek out someone who benefits from the current arrangement and ask them to describe it as fairly as they can."],
  ['sources', "An archive, a log or a complaints file that nobody has asked to see in years; dull records often hold the surprise that interviews miss."],
  ['sources', "A practitioner on the lowest rung, who can tell you what the policy really does by Tuesday afternoon rather than what it says on paper."],
  ['sources', "A specialist from an unrelated field that faces the same structural problem under a different name, whose vocabulary might reframe everything."],
  ['sources', "The person who was right early and ignored. Ask what they saw, and what they think everyone else needed in order to listen."],
  ['sources', "Someone who changed their mind about {topic}, in either direction, because the reason for the change is a ready-made argument."],
  ['sources', "The ordinary user with a homemade workaround, since a workaround is a map of every place the official version fails."],
  ['sources', "A critic respected even by the people they criticise, so the objection arrives with credibility already attached."],
  ['sources', "Records that exist but have never been charted, such as shift logs, waiting lists or repair tickets. Ask who keeps them and whether you can look."],
  ['sources', "A visit to where the work happens, to learn what only watching shows: who waits, who hurries, who is quietly routed around."],
  ['sources', "Treat {place} as a source of its own: what has it recorded, tolerated and quietly preserved that no interview would ever volunteer?"],

  // ── counter ─────────────────────────────────────────────────────────────────
  ['counter', "The strongest objection may be that the whole pattern is coincidence, so the piece needs one example that coincidence cannot explain."],
  ['counter', "Survivorship: the cases you collected are the ones that lasted long enough to be found, so ask who is missing from the evidence."],
  ['counter', "Who pays if readers follow the advice? A fair opponent will point to someone for whom the sensible-sounding conclusion is a bad deal."],
  ['counter', "The reversed-causation objection: perhaps the effect you describe is really the cause, and the piece owes the reader a reason to prefer your direction."],
  ['counter', "A reader with lived experience of the opposite, who will trust what they saw with their own eyes over any argument you assemble."],
  ['counter', "The it-only-works-with-resources objection: does the conclusion hold for people without time, money or permission, or only for people already well placed?"],
  ['counter', "Someone who agrees with your conclusion for poor reasons. Their support is a counter-argument in disguise, and the piece may need to separate itself from it."],
  ['counter', "The tradition objection: an old habit may persist because it solves something nobody has named, so learn what quiet job it performs before attacking it."],
  ['counter', "A time-shift objection: would the argument still hold in a different era, a different climate or after a bad year? If not, narrow the claim."],
  ['counter', "The best opponent is not a villain but a friend who wants the same outcome and disagrees about the path. Imagine their strongest case before answering it."],
  ['counter', "The scale objection: it may be true for one household or team and false for a thousand, so where exactly does your claim stop working?"],
  ['counter', "What would the argument look like if the other side had your best evidence? Try building their case from the same material."],

  // ── reader ──────────────────────────────────────────────────────────────────
  ['reader', "A reader who already half-agrees and mostly wants permission, who is best served by the clearest reasons rather than the loudest ones."],
  ['reader', "A newcomer afraid of looking foolish, who needs the embarrassing basics handled without condescension and the jargon explained exactly once."],
  ['reader', "The expert who is tired of being explained to, and will stay only if the piece shows them something they have not already filed away."],
  ['reader', "A reader making a real decision this week, who needs the trade-offs and the hidden cost far more than the backstory."],
  ['reader', "Someone reading in the gap between two tasks. What is the single thing that must survive if they stop at the end of the first section?"],
  ['reader', "A reader who was personally burned by {topic} and arrives braced for being told it was their own fault."],
  ['reader', "The sceptic who reads to the end only to find the weak point, which raises the question of what they would forward to a friend with a sneer."],
  ['reader', "A reader who will pass this on to someone who has to act on it, the manager, the relative or the committee. What does that second person need on the page?"],
  ['reader', "A smart outsider with no background and plenty of curiosity. Explaining {topic} to them over dinner, where would you reach for a comparison?"],
  ['reader', "The reader's mood on arrival: anxious, bored, defensive or hopeful. The same material needs a different pace for each, so pick one honestly."],
  ['reader', "A reader who will argue in the comments, which means every claim they could attack needs a visible reason sitting right beside it."],
  ['reader', "Someone from the group the piece is about, reading over everyone else's shoulder. Would they recognise themselves, or feel studied from a distance?"],

  // ── case ────────────────────────────────────────────────────────────────────
  ['case', "A case where everything was done right and it failed anyway, which exposes the limits of the standard advice better than any success could."],
  ['case', "Two cases that began almost identically and ended differently, with the piece hunting for the one early difference that mattered."],
  ['case', "A boring case in which nothing dramatic happened, offered as proof that a system working properly looks like nothing at all."],
  ['case', "An example from a neighbouring field that shares the underlying structure but not the vocabulary, so the reader sees the pattern without their preconceptions."],
  ['case', "The case that makes your own thesis look shaky, included deliberately and examined openly, so the reader trusts everything that follows."],
  ['case', "An account told by the least involved witness, the neighbour, the temp, the person who happened to be standing nearby, whose small details survive when official versions blur."],
  ['case', "A before-and-after pair, the same place or routine at two different moments, so the change can be seen without a single adjective."],
  ['case', "An example the reader can test at home in an afternoon with things they already own, so they leave with a result rather than an opinion."],
  ['case', "A case where a wrong version of events outlived the evidence, traced through everyone who repeated it, to show how a story hardens."],
  ['case', "The best example is small, odd and physical, the kind of detail a reader repeats to a friend a week later."],
  ['case', "An example drawn from your own mistake, told without flattering anyone, including yourself."],
  ['case', "A cautionary case about {topic} where the warning signs were visible to everyone and acted on by no one, and what kept all those eyes from moving."],

  // ── myth ────────────────────────────────────────────────────────────────────
  ['myth', "Hunt for the assumption inside {topic} that everyone repeats and nobody has traced back to a source. The tracing itself may be the story."],
  ['myth', "The comforting myth that the trouble comes from one bad actor, when the whole setup rewards ordinary people for doing the same thing."],
  ['myth', "The belief that the experts must have settled the question already, tested by finding out who actually asked it and when they stopped."],
  ['myth', "A neat origin story everyone tells about how the thing began. Does it survive a look at who first told it and what they gained?"],
  ['myth', "The myth of the single turning point, the idea that one moment changed everything, when a slow pile of small decisions did the work."],
  ['myth', "A myth that survives because it flatters the person repeating it. Ask whom it makes feel clever, safe or innocent."],
  ['myth', "The rule of thumb everyone in the field obeys: where it came from, what it was a shortcut for, and whether that problem still exists."],
  ['myth', "The assumption that people who disagree simply have not understood, tested by finding the ones who have understood completely and still disagree."],
  ['myth', "A myth about who is affected: the stock picture of the typical person involved, compared with the people actually in the room."],
  ['myth', "Sorting the folk wisdom around {topic} into three piles, what holds, what is half true and what only sounds wise, and letting the middle pile become the piece."],
  ['myth', "The myth that simple problems have simple causes, explored by following one small irritating effect back through a surprisingly tangled set of reasons."],

  // ── scope ───────────────────────────────────────────────────────────────────
  ['scope', "Shrink the piece to a single decision: the one moment where someone chose between two reasonable options, and everything that pressed on that choice."],
  ['scope', "Limit it to the first hour or the first week of the experience, the part newcomers actually face, and leave the long road for another piece."],
  ['scope', "One person, one place and one season, with the claim kept only as big as that frame can honestly carry."],
  ['scope', "Swap the sweeping claim for the smallest version you could defend in front of an expert, then see whether the piece got more interesting or less."],
  ['scope', "Decide what the piece is deliberately not about and tell the reader early; admitting the border makes everything inside it feel safer."],
  ['scope', "Narrow to the part that experts actually argue about, skipping the settled background a reader can easily look up elsewhere."],
  ['scope', "One question, one answer: if the piece cannot be summed up as a single honest question, it is probably two articles hiding in one."],
  ['scope', "The exception test: build around the single case that breaks the general rule rather than around the rule, since the exception is smaller and teaches more."],
  ['scope', "Cut by audience instead of subject: the same topic, but only for the person facing one specific situation, with everything else dropped."],
  ['scope', "Break the large subject into the parts that could each stand alone, then pick the one you would be most annoyed to see someone else cover."],
  ['scope', "Draw the line at change: cover only the part of {topic} that is different from how it was a generation ago."],

  // ── format ──────────────────────────────────────────────────────────────────
  ['format', "A field guide of short entries for the types or situations a reader will meet, each with how to recognise it and what not to do."],
  ['format', "A glossary where each term is a doorway, and every definition quietly turns into a small story about the people who needed the word."],
  ['format', "A conversation between two people who disagree about {topic} and respect each other, arranged so the reader can switch sides midway."],
  ['format', "An annotated timeline in which the notes are the real article and the markers are just scaffolding, so the reader scans first and reads second."],
  ['format', "A checklist where every item has a short reason attached, so it works for the hurried reader and still persuades the doubtful one."],
  ['format', "A diary of one week spent doing the thing properly, with the failures left in, shaped into a practical guide the reader can follow."],
  ['format', "A decision tree: the reader answers a handful of honest questions about their own situation and lands in the section made for them."],
  ['format', "A letter-style explainer to one specific person who is about to make a mistake, built so everyone else can read over their shoulder."],
  ['format', "A profile of a process instead of a person, following a repair, an application or a harvest from first step to last and meeting people only as they appear."],
  ['format', "A question-and-answer piece with an unlikely expert, someone with deep practical knowledge and no public profile, whose replies are the entire article."],
  ['format', "A guided tour for a first visit, moving through a place or process in the order a newcomer would meet it, pausing where locals no longer notice."],
  ['format', "A set of side-by-side comparison cards, each pairing a common assumption with the more complicated truth, so the structure itself carries the argument."],

  // ── question ────────────────────────────────────────────────────────────────
  ['question', "What do you want the reader to do differently on Monday morning, and is that something the piece can actually earn?"],
  ['question', "What is the one claim you would defend even if every example you have collected turned out to be unrepresentative?"],
  ['question', "Who would be unhappy to read the finished piece about {topic}, and would they be unhappy because it is unfair or because it is accurate?"],
  ['question', "What would you need to see to change your mind about {topic}, and have you actually gone looking for it?"],
  ['question', "Why this piece, and why now? If the honest answer is only that it was assigned, what makes it matter to someone who was not?"],
  ['question', "What does the reader already believe, and what is the smallest honest step from there to where the piece wants them to end up?"],
  ['question', "Which part of the piece are you most afraid to be wrong about, and who could check it for you?"],
  ['question', "If the piece could keep only a single example, which one, and what does that choice reveal about your real argument?"],
  ['question', "What are you assuming the reader already knows, and could a friend outside the subject confirm it in a single phone call?"],
  ['question', "What is your own stake in {topic}, and does the reader deserve to know it before deciding how far to trust you?"],
  ['question', "What is the most boring true version of this piece, and what does it have that the exciting version quietly lacks?"],
  ['question', "Where would a fair-minded sceptic stop reading, and is that exactly the spot where your evidence is thinnest?"],
  ['question', "What is the smallest finished version of this piece that would still be useful, and what are you afraid of losing by stopping there?"],
  ['question', "Where does {theme} show up in {topic}, and are you reporting it or projecting it?"],
];
