// Idea bank: article. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
// Strings use double quotes so apostrophes read naturally; the text itself never contains quotation marks.
// Ideas are framings and questions about the writer's own subject, never facts about it.
export default [
  // ── spark ───────────────────────────────────────────────────────────────────
  ['spark', "An explanation of {topic} told entirely through the ordinary objects that give it away, each one handled like evidence at a hearing."],
  ['spark', "A thought experiment about {topic}: imagine it designed from scratch by people who have never seen the current version, and ask which of today's oddities they would never think to invent."],
  ['spark', "A how-to for a skill you are still bad at, where the failures are the useful part and the expert advice only makes cameos."],
  ['spark', "One ordinary afternoon reported through three people with very different stakes, with the real argument hiding in what each of them leaves out."],
  ['spark', "The dullest question about {topic}, treated with the seriousness of a mystery and chased until it stops being dull."],
  ['spark', "A guide for someone who will use the advice exactly once, at the worst possible moment, and needs it to work with no background at all."],
  ['spark', "An affectionate audit of a ritual that everyone in a field performs and nobody has ever asked a newcomer to justify."],
  ['spark', "A forecast for {topic}: what is building, what is clearing and what is likely to catch people unprepared, delivered with the dry confidence of a weather report."],
  ['spark', "A piece built around the one question people are privately embarrassed to ask about {topic}, chased all the way to a real answer."],
  ['spark', "An article addressed to whoever inherits the problem a generation from now, explaining what today's people got right by accident and wrong on purpose."],
  ['spark', "Two things everyone treats as rivals, shown to be the same process seen from opposite ends."],
  ['spark', "A piece in which {theme} is never named but explains every odd choice people make around {topic}."],

  // ── angle ───────────────────────────────────────────────────────────────────
  ['angle', "Maintenance instead of launch: skip the announcement and look at the unglamorous upkeep behind {topic}, and at whoever does it."],
  ['angle', "Waiting as an angle: where people are made to wait around {topic}, and what the queue reveals about whose time counts."],
  ['angle', "The near miss as an angle: the time something almost went wrong, and what the almost reveals that a clean success never would."],
  ['angle', "Seeing {topic} as a negotiation between two groups who each sincerely believe they are the reasonable ones."],
  ['angle', "A history of the word itself: has the term people use for this subject drifted in meaning, and what did each shift let them stop noticing?"],
  ['angle', "The beginner's mistake as an angle: what the standard first error teaches that the polished expert version hides."],
  ['angle', "The cost of the accepted fix: the problem gets the attention, so look instead at what the popular solution takes from people who never agreed to pay."],
  ['angle', "One small place, a single workshop, street or office, treated as a working model of the larger question, with the big picture earning its place afterward."],
  ['angle', "The shape of {topic} across one person's whole life, instead of in a single frozen moment."],
  ['angle', "The exception as an angle: the one person or place that ought to follow the pattern and refuses, whose reasons expose the pattern's hidden assumptions."],
  ['angle', "Regret as an angle: ask people who made the standard choice years ago what they wish they had known, and listen for the answer that repeats."],
  ['angle', "The scale flip: the kitchen-table version of a story usually told in institutional terms, or the institutional version of one usually told at the kitchen table."],
  ['angle', "An angle that asks what {theme} has to do with {topic}, since the odd pairing may turn out to be the whole piece."],

  // ── hook ────────────────────────────────────────────────────────────────────
  ['hook', "The procedure as a hook: the ordinary steps of a routine laid out in calm order, until one step turns out to hold the whole story."],
  ['hook', "A tiny, specific failure, a missed bus, a wrong form, a ruined batch, that widens until it is plainly about {topic}."],
  ['hook', "An opening where the writer admits a belief the reporting later took apart, so the reader enters as a fellow sceptic rather than a student."],
  ['hook', "A question a child would ask about {topic}, taken seriously, since the honest answer may be harder than the question sounds."],
  ['hook', "A puzzle hook: two facts that cannot both be true as they stand, set side by side, with a promise to reconcile them."],
  ['hook', "An opening set somewhere readers rarely see, a back office, a loading bay or a waiting room, chosen because the place itself already makes half the argument."],
  ['hook', "Starting in the middle of an argument between two people who both have a point, with the article as the thing that eventually referees it."],
  ['hook', "A hook from absence: begin with what is conspicuously missing, a silent room, an empty shelf, a form with no complaints, and make the reader want the reason."],
  ['hook', "A quiet-stakes opening: a small decision the reader will face this week, followed by a slow reveal of how much hangs on it."],
  ['hook', "The last ordinary minute before something changed, held still long enough for the reader to spot what everyone at the time missed."],
  ['hook', "Authority flipped by leading with the most junior or least credentialled voice in the story, and promising that the experts will have to answer them."],
  ['hook', "A competent person confidently doing the wrong thing for good reasons, so the reader slowly realises they would have done the same."],

  // ── headline ────────────────────────────────────────────────────────────────
  ['headline', "A headline direction that promises a verdict and withholds the reasoning, so the click comes from wanting to see the argument rather than the answer."],
  ['headline', "Two ordinary words that should not share a sentence, joined in a headline so the reader needs the piece itself to reconcile them."],
  ['headline', "Plain and literal over something surprising: a calm headline that lets the content do all the startling."],
  ['headline', "The question headline, on one condition: the piece answers it honestly, and the answer is more interesting than a plain no."],
  ['headline', "The reader's specific worry, named in their own vocabulary rather than the industry's, so the headline sounds like a thought they were already having."],
  ['headline', "A headline modelled on a proverb or house rule, keeping its rhythm and bending its meaning just enough to point at {topic}."],
  ['headline', "A headline that holds a gain and its cost side by side, the thing won and the thing given up, and leaves the reader to weigh them."],
  ['headline', "Result or mystery as a headline promise: which one could the finished piece honestly keep, and which would only pull the reader in?"],
  ['headline', "The unexpected person or object leading the headline instead of the subject, with the connection saved for the subhead."],
  ['headline', "A deliberately small headline for a large subject, narrowing to one street, one tool or one afternoon, so the scale itself is the intrigue."],
  ['headline', "The conclusion stated in the headline as a calm, almost boring fact, since the surprise lives in why it is true."],
  ['headline', "A headline that advertises what the piece will not claim, so honesty about its limits becomes the draw."],
  ['headline', "A headline pitched at the sceptic, built to make them curious instead of defensive before they have read a word of the argument."],

  // ── structure ───────────────────────────────────────────────────────────────
  ['structure', "The conclusion up front, then the rest of the piece spent on the three strongest reasons to doubt it, ending on whether it survives."],
  ['structure', "Frame and return: one small scene at the start, a long departure into the argument, then back to the scene so it now means something different."],
  ['structure', "A piece organised as a trial, with sections for the case for, the case against, the witness nobody called, and a verdict the writer is willing to reverse."],
  ['structure', "Reverse chronology that begins with the outcome and peels back one decision at a time until the reader meets the first, innocent choice."],
  ['structure', "Each section closes on the objection the next section has to answer, so the argument moves like a conversation with a polite sceptic."],
  ['structure', "Sections ordered by confidence instead of chronology: what is firmly known first, then what is probably true, then what is still argued over, ending on the open question."],
  ['structure', "A relay structure that follows one object, form or request through every pair of hands it passes, so each section is a handoff and the problems live in the gaps."],
  ['structure', "Two timelines braided together, the official version and the lived version, converging only in the final section."],
  ['structure', "A clean first half that states the accepted story and a second half that dismantles it, with the hinge placed exactly in the middle."],
  ['structure', "A ladder of increasingly uncomfortable questions, each answered before the reader is allowed to climb to the next."],
  ['structure', "A long central section framed by brief interludes from affected people, each one a short burst that works like a chorus."],
  ['structure', "An alternating rhythm of how and why, where every practical step is followed by the reason a sceptic might refuse to take it."],
  ['structure', "A deliberate hole at the centre: the one thing the piece cannot find out, circled by everything that is known, so the gap becomes the structure."],

  // ── sources ─────────────────────────────────────────────────────────────────
  ['sources', "Look for the person who used to do this job and left, since former insiders can explain the unwritten rules the current ones no longer notice."],
  ['sources', "Find whoever writes the manual, the training notes or the checklist, and ask what they had to leave out."],
  ['sources', "Someone who benefits from the current arrangement around {topic}, asked to describe it as fairly as they can."],
  ['sources', "An archive, a log or a complaints file that few people ever open; dull records can hold the surprise that interviews miss."],
  ['sources', "A practitioner on the lowest rung, who can tell you what the policy really does by Tuesday afternoon rather than what it says on paper."],
  ['sources', "A specialist from an unrelated field that faces the same structural problem under a different name, whose vocabulary might reframe everything."],
  ['sources', "The person who was right early and ignored. Ask what they saw, and what they think everyone else needed in order to listen."],
  ['sources', "Someone who changed their mind about {topic}, in either direction, because the reason for the change is a ready-made argument."],
  ['sources', "The ordinary user with a homemade workaround, since a workaround is a map of every place the official version fails."],
  ['sources', "A critic respected even by the people they criticise, so the objection arrives with credibility already attached."],
  ['sources', "Earlier editions of the rulebook, form or guidance, compared one version to the next, since each added clause may mark something that once went wrong."],
  ['sources', "A visit to where the work happens, to learn what only watching shows: who waits, who hurries, who is quietly routed around."],
  ['sources', "Treat {place} as a source of its own: what has it recorded, tolerated and preserved that no interview would ever volunteer?"],
  ['sources', "Whoever gets the phone call when something goes wrong, the repairer, the receptionist or the on-call volunteer, since they see failures that rarely travel upward."],

  // ── counter ─────────────────────────────────────────────────────────────────
  ['counter', "What if the whole pattern is coincidence? The piece needs at least one example that coincidence cannot explain."],
  ['counter', "Survivorship check: if the cases you collected are only the ones that lasted long enough to be found, who is missing from the evidence?"],
  ['counter', "Picture a reader who follows your advice to the letter and it goes badly for them. What condition did the advice quietly depend on?"],
  ['counter', "Reversed causation: what if the effect you describe is really the cause, and what in your material lets you prefer your direction?"],
  ['counter', "A reader with lived experience of the opposite, who will trust what they saw with their own eyes over any argument you assemble."],
  ['counter', "Does the conclusion hold for people without time, money or permission, or only for people already well placed to act on it?"],
  ['counter', "Someone who agrees with your conclusion for poor reasons. Their support is a counter-argument in disguise, and the piece may need to separate itself from it."],
  ['counter', "An old habit that looks pointless may be solving a problem nobody has named, so find out what hidden job it performs before arguing against it."],
  ['counter', "Would the argument still hold in a different decade, a different place or after a bad year? If not, narrow the claim."],
  ['counter', "The best opponent is not a villain but a friend who wants the same outcome and disagrees about the path. Imagine their strongest case before answering it."],
  ['counter', "True for one household or team and false for a thousand: where exactly does your claim stop working?"],
  ['counter', "What would the argument look like if the other side had your best evidence? Try building their case from the same material."],
  ['counter', "Where does the whole argument lean on one person's word, and what happens to it if they turn out to be wrong?"],
  ['counter', "An opponent may accept every fact you gather and still reject what the central word is allowed to mean, so where does your definition carry the argument?"],

  // ── reader ──────────────────────────────────────────────────────────────────
  ['reader', "The reader who already half-agrees and mostly wants permission, and who is best served by the clearest reasons rather than the loudest ones."],
  ['reader', "A newcomer afraid of looking foolish, who needs the embarrassing basics handled without condescension and the jargon explained exactly once."],
  ['reader', "The expert who is tired of being explained to, and will stay only if the piece shows them something they have not already filed away."],
  ['reader', "Someone making a real decision this week, who needs the trade-offs and the hidden cost far more than the backstory."],
  ['reader', "Reading in the gap between two tasks: what is the single thing that must survive if the reader stops at the end of the first section?"],
  ['reader', "A reader who was personally burned by {topic} and arrives braced for being told it was their own fault."],
  ['reader', "The reader who returns months later to look one thing up: what would they hope to find again, and how would they know where to look?"],
  ['reader', "A reader who will pass this on to someone who has to act on it, the manager, the relative or the committee. What does that second person need on the page?"],
  ['reader', "A smart outsider with plenty of curiosity and no background: over dinner, where would you reach for a comparison to explain {topic}?"],
  ['reader', "The reader's mood on arrival: anxious, bored, defensive or hopeful. The same material needs a different pace for each, so pick one honestly."],
  ['reader', "One claim pulled out of the piece and carried into an argument elsewhere: which claim is most exposed, and what context has to travel with it?"],
  ['reader', "Someone from the group the piece is about, reading over everyone else's shoulder. Would they recognise themselves, or feel studied from a distance?"],
  ['reader', "A reader who has heard this argument before from a source they distrust, and who arrives assuming the piece is more of the same. What would convince them it is not?"],

  // ── case ────────────────────────────────────────────────────────────────────
  ['case', "A case where everything was done right and it failed anyway, which exposes the limits of the standard advice better than any success could."],
  ['case', "Two cases that began almost identically and ended differently, with the piece hunting for the one early difference that mattered."],
  ['case', "A boring case in which nothing dramatic happened, offered as a picture of what a system working properly looks like."],
  ['case', "A case from long ago that shows the same problem in older clothes, so readers stop treating it as a product of the present moment."],
  ['case', "The case that makes your own thesis look shaky, included deliberately and examined openly, so the reader trusts everything that follows."],
  ['case', "An account from the least involved witness, the neighbour, the temp, the person who happened to be standing nearby, whose small details survive when official versions blur."],
  ['case', "A before-and-after pair, the same place or routine at two different moments, so the change can be seen without a single adjective."],
  ['case', "Where the subject allows it, an experiment the reader can run in an afternoon with things they already own, so they leave with a result rather than an opinion."],
  ['case', "The borderline case, sitting between two categories people usually keep apart, showing why the line is harder to draw than it looks."],
  ['case', "A success that was copied somewhere else and failed there, exposing what the original depended on without anyone noticing."],
  ['case', "An example drawn from your own mistake, told without flattering anyone, including yourself."],
  ['case', "A cautionary case about {topic} in which the warning signs were visible to everyone and acted on by no one, and what kept all those eyes from moving."],
  ['case', "The person who ignored the standard advice and found it worked, examined for what was special about their situation."],

  // ── myth ────────────────────────────────────────────────────────────────────
  ['myth', "Hunt for the assumption about {topic} that everyone repeats and nobody has traced back to a source. The tracing itself may be the story."],
  ['myth', "The comforting story that one bad actor is behind the trouble, tested by asking whether the setup would produce the same behaviour from anyone who stepped into the role."],
  ['myth', "The idea that the experts must have settled the question already, tested by finding out who actually asked it and when the asking stopped."],
  ['myth', "The belief that the choice is between two sides, tested by finding the people who fit neither camp and asking why neither side speaks for them."],
  ['myth', "The story of a single turning point, tested by listing the smaller decisions around that moment and asking whether the famous one was the hinge or just the part that got noticed."],
  ['myth', "A myth that persists because it flatters whoever repeats it. Ask whom it makes feel clever, safe or innocent."],
  ['myth', "Any rule of thumb that everyone in the field obeys: what problem was it a shortcut for, and does that problem still exist?"],
  ['myth', "The assumption that people who disagree simply have not understood, tested by finding the ones who have understood completely and still disagree."],
  ['myth', "A myth about who is affected: the stock picture of the typical person involved, compared with the people actually in the room."],
  ['myth', "Sorting the folk wisdom around {topic} into three piles, what holds, what is half true and what only sounds wise, and letting the middle pile become the piece."],
  ['myth', "The assumption that someone would have fixed it by now, examined by asking who would have to act, what it would cost them and what they would lose by fixing it."],
  ['myth', "The golden-age belief that things used to work better, tested against what the people who lived through those years actually complained about."],
  ['myth', "The prediction that a new tool or method will fix everything, or ruin everything, set beside what happened the last time a prediction like it was made."],

  // ── scope ───────────────────────────────────────────────────────────────────
  ['scope', "Shrink the piece to a single decision: the one moment where someone chose between two reasonable options, and everything that pressed on that choice."],
  ['scope', "Limit it to the first hour or the first week of the experience, the part newcomers actually face, and leave the long road for another piece."],
  ['scope', "One person, one place and one season, with the claim kept only as big as that frame can honestly carry."],
  ['scope', "Swap the sweeping claim for the smallest version you could defend in front of an expert, then see whether the piece got more interesting or less."],
  ['scope', "Decide what the piece is deliberately not about and tell the reader early; admitting the border makes everything inside it feel safer."],
  ['scope', "Narrow to the part that experts actually argue about, skipping the settled background a reader can easily look up elsewhere."],
  ['scope', "One question, one answer: if the piece cannot be summed up as a single honest question, it may be two pieces sharing a headline."],
  ['scope', "Scope by what can be verified: keep only the claims you could check in person or against a primary record, and see what shape the piece takes."],
  ['scope', "Cut by audience instead of subject: the same topic, but only for the person facing one specific situation, with everything else dropped."],
  ['scope', "Break the large subject into the parts that could each stand alone, then pick the one you would be most annoyed to see someone else cover."],
  ['scope', "Draw the line at change: cover only the part of {topic} that is different from how it used to be, and leave the permanent background alone."],
  ['scope', "Trade breadth for depth: choose the one detail in {topic} that keeps raising questions, and let the piece go as far into it as it can, ignoring the survey."],

  // ── format ──────────────────────────────────────────────────────────────────
  ['format', "A field guide of short entries for the types or situations a reader will meet, each with how to recognise it and what not to do."],
  ['format', "A glossary where each term is a doorway, and every definition turns into a small story about the people who needed the word."],
  ['format', "A conversation between two people who disagree about {topic} and respect each other, arranged so the reader can switch sides midway."],
  ['format', "An annotated timeline in which the notes are the real article and the markers are just scaffolding, so the reader scans first and reads second."],
  ['format', "A checklist where every item has a short reason attached, so it works for the hurried reader and still persuades the doubtful one."],
  ['format', "A close reading of one ordinary document, a form, a sign or a rulebook page, with the whole argument built from what each line assumes."],
  ['format', "A decision tree: the reader answers a handful of honest questions about their own situation and lands in the section made for them."],
  ['format', "A letter-style explainer to one specific person who is about to make a mistake, built so everyone else can read over their shoulder."],
  ['format', "A profile of a process instead of a person, following a repair, an application or a harvest from first step to last and meeting people only as they appear."],
  ['format', "A question-and-answer piece with an unlikely expert, someone with deep practical knowledge and no public profile, whose replies are the entire article."],
  ['format', "A guided tour for a first visit, moving through a place or process in the order a newcomer would meet it, pausing where locals no longer notice."],
  ['format', "A set of side-by-side comparison cards, each pairing a common assumption with the more complicated truth, so the structure itself carries the argument."],
  ['format', "An obituary-shaped piece for something on its way out, a practice, tool or job, treating its quirks as accomplishments and asking what leaves with it."],

  // ── question ────────────────────────────────────────────────────────────────
  ['question', "What do you want the reader to do differently on Monday morning, and is that something the piece can actually earn?"],
  ['question', "Which single claim would you still defend if every example you have collected turned out to be unrepresentative?"],
  ['question', "Who would be unhappy to read the finished piece about {topic}, and would they be unhappy because it is unfair or because it is accurate?"],
  ['question', "What would you need to see to change your mind about {topic}, and have you actually gone looking for it?"],
  ['question', "Why this piece, and why now? Set aside the deadline or the assignment: what makes it matter to someone who never heard of either?"],
  ['question', "What does the reader already believe, and what is the smallest honest step from there to where the piece wants them to end up?"],
  ['question', "Which part of the piece are you most afraid to be wrong about, and who could check it for you?"],
  ['question', "If the piece could keep only a single example, which one, and what does that choice reveal about your real argument?"],
  ['question', "What are you assuming the reader already knows, and could a friend outside the subject confirm it in a single phone call?"],
  ['question', "What is your own stake in {topic}, and does the reader deserve to know it before deciding how far to trust you?"],
  ['question', "Strip the piece down to its most boring true version: what does that version have that the exciting one lacks?"],
  ['question', "Where would a fair-minded sceptic stop reading, and is that exactly the spot where your evidence is thinnest?"],
  ['question', "Which part of the material do you keep wanting to leave out, and is that because it is dull or because it complicates your argument?"],
  ['question', "Where does {theme} show up in {topic}, and are you reporting it or projecting it?"],
  ['question', "Whose reputation, livelihood or privacy is on the line in this piece, and have they had a fair chance to answer?"],
];
