// Idea bank: character. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
// Strings use double quotes so apostrophes read naturally; the text itself never contains quotation marks.
export default [
  // ── spark: a whole person in one breath ────────────────────────────────────
  ["spark", "A river pilot who carries every shifting sandbar of a waterway in memory, and is now the only living map of a place scheduled to be flooded."],
  ["spark", "A lifelong understudy who knows every role in the company by heart, has never once been asked to go on, and is the only person who understands how the whole production really holds together."],
  ["spark", "Someone who has outlived everyone who ever used their first name, and is now deciding who, if anyone, gets to use it."],
  ["spark", "{Who} keeps a packed bag by the door and a rehearsed plan for every disaster except the one that is actually coming."],
  ["spark", "A shipboard intelligence built to be unable to lie, whose crew has learned to ask only the questions they can bear the answers to."],
  ["spark", "A funeral caterer who can read a family's whole history from what the mourners reach for and what they quietly refuse."],
  ["spark", "The most forgettable background figure in your project, the one who only opens doors or delivers messages, has been swallowing an ambition for years, and it has just found a use for all that unnoticed access."],
  ["spark", "A ghost bound not to a house or a death but to an unfinished argument, who cannot move on until a living person agrees to finish it."],
  ["spark", "{Who} inherits a debt instead of a fortune, owed to someone who has waited patiently for exactly this generation."],
  ["spark", "An in-house apologiser for a powerful family, who has said sorry on everyone else's behalf for so long that the personal debts have gone uncounted."],
  ["spark", "A card-room hustler who has lost on purpose for a living for so long that they have begun to miss the feeling of really trying."],
  ["spark", "A hedge-witch whose only dependable talent is persuading unwelcome things to leave quietly, from damp and pests to ghosts and tax collectors."],
  ["spark", "{Who} belongs so completely to {place} that being anywhere else produces a smaller, less certain version of the same person."],
  ["spark", "Someone whose private life is a quiet counterexample to {theme}, and who has no idea anyone has noticed."],
  ["spark", "A landlord the whole building despises, who has not raised one particular tenant's rent in all these years and refuses to say why."],

  // ── want ───────────────────────────────────────────────────────────────────
  ["want", "Someone wants to be forgiven by a person who does not even remember the offence, and has to decide whether reminding them counts as part of the apology."],
  ["want", "{Who} wants to be left in peace, and the real test of that wish arrives the day everyone finally obliges."],
  ["want", "A want so small it embarrasses the person who has it, a particular parking space or the first slice of a new loaf, defended with the seriousness of a border dispute."],
  ["want", "A character fighting to have an official record corrected, a name, a date, a cause of death, only to find that too many people have since built their lives on the error."],
  ["want", "A character determined to vanish completely, whose every workable plan needs help from the one person who would be hurt most by it."],
  ["want", "Being needed is the whole want: a character who arranges small, plausible emergencies so that people keep turning up at the door."],
  ["want", "{Who} wants to finish what a dead mentor left half-done, and has just found evidence that it was abandoned on purpose."],
  ["want", "The second chance the character has longed for, at something they once did badly, finally arrives in a form that is smaller, stranger, and far more humiliating than the original."],
  ["want", "{Who} wants revenge and a place at the family table in equal measure, and every step toward the first closes a door to the second."],
  ["want", "{Who} wants to stay underestimated, because it is the only way anything has ever got done, and has just been offered an honour that would end it."],
  ["want", "A long-haul spacer wants nothing more than a small, boring house with a garden, and every well-paid contract takes that garden one star further out of reach."],
  ["want", "The exact opposite of {theme} is what this character secretly wants most, and they have not noticed that want steering every choice."],
  ["want", "{Who} wants to leave {place} behind and has a dozen respectable reasons for staying that all turn out to be one reason."],
  ["want", "Someone whose every want is on behalf of another person, to the point where they could not name a single desire of their own if asked."],

  // ── flaw ───────────────────────────────────────────────────────────────────
  ["flaw", "Generosity that is really control: every gift arrives with unspoken strings, and the giver is baffled when people start avoiding their kindness."],
  ["flaw", "{Who} cannot bear being thanked, and deflects, jokes, or leaves the room whenever gratitude is about to land, so the people who meant it begin to feel their kindness was refused."],
  ["flaw", "Pride disguised as humility: someone who loudly volunteers for the worst job so that no one else can be seen doing it better."],
  ["flaw", "{Who} has a gift for being right at precisely the wrong moment, delivering the accurate, unwelcome truth at the one time it can only wound."],
  ["flaw", "An unshakable belief in being the reasonable one, which turns every complaint about the character into proof that the complainer is the problem."],
  ["flaw", "Someone so afraid of being a burden that they refuse all help, until the refusing becomes the heaviest thing the people around them have to carry."],
  ["flaw", "Cowardice that passes for patience: a character who waits for the perfect moment so skilfully that it never arrives."],
  ["flaw", "A talent for charm that has never had to be sincere, so when sincerity is finally required there is no practised version of it to reach for."],
  ["flaw", "{Who} cannot tolerate not knowing, and will open the letter, the door, or the sealed box even when everything suggests the not-knowing was the protection."],
  ["flaw", "A past retouched so lovingly in memory that no present person, place, or chance can ever measure up to it."],
  ["flaw", "A person so used to being good at things that they refuse to be a beginner, so every new door stays shut and the shut doors are called standards."],
  ["flaw", "A hero who cannot refuse a quest, any quest, from any stranger, and has never thought to ask who stands to benefit."],
  ["flaw", "A loyalty so total that it has never been examined, and is being spent every day on someone who stopped deserving it long ago."],
  ["flaw", "{Who} is certain they know the unwritten rules of {place} better than anyone, and enforces them on newcomers who never agreed to them."],
  ["flaw", "A habit of claiming to have known every piece of news already, which has cornered the character into never being seen to learn anything."],

  // ── contradiction ──────────────────────────────────────────────────────────
  ["contradiction", "A devoted rule-keeper with one carefully guarded exception, and it is the very rule everyone else depends on them to keep."],
  ["contradiction", "{Who} is famous for honesty and maintains a single lie so carefully that it has become the load-bearing wall of an otherwise truthful life."],
  ["contradiction", "A person who is harsh with the people they love and tender with strangers, because strangers have not yet had the chance to disappoint them."],
  ["contradiction", "A devout believer who no longer feels anything in worship and keeps showing up out of loyalty to the person they used to be."],
  ["contradiction", "{Who} insists they are the easiest person in the world to please, and is quietly furious with everyone who takes them at their word."],
  ["contradiction", "An optimist whose cheerfulness is a daily discipline rather than a temperament, upheld at visible cost and starting to slip."],
  ["contradiction", "A famously lazy person who works tirelessly on one hidden project, with the public idleness serving as camouflage."],
  ["contradiction", "Scorn for sentimentality, and a place the character never opens where every scrap of evidence of the people they have loved is kept, sorted and labelled."],
  ["contradiction", "A fatalist who plans obsessively, because planning is the only way they have found to stay calm about what they believe cannot be avoided."],
  ["contradiction", "A rigorous sceptic with one absurd superstition, which is the only part of them that never gets examined."],
  ["contradiction", "Someone whose job requires them to be feared and who is scrupulously gentle off duty, and who has begun to lose track of which version is the performance."],
  ["contradiction", "A famous miser who gives money away in a pattern nobody has yet worked out, and who bristles whenever anyone calls it generosity."],
  ["contradiction", "{Who} is the most welcoming person in {place} and has never once invited anyone home."],

  // ── secret ─────────────────────────────────────────────────────────────────
  ["secret", "A beloved local tradition that the character secretly invented long ago, as a joke or a kindness, and now watches everyone defend as ancient."],
  ["secret", "{Who} knows how the event that everyone remembers differently really ended, and has let the tidier version stand to protect someone."],
  ["secret", "A second life in another city, kinder and braver than the first, and the real trouble is that the invented self is the better person."],
  ["secret", "A secret that is fragile rather than shameful: a private joy, hobby, or love kept hidden because the world would flatten it into something ordinary."],
  ["secret", "{Who} is hiding that a great talent has gone, and every public performance is now a careful impersonation of their own former self."],
  ["secret", "Someone has learned that the shop, farm, or workplace everyone relies on is going to close, and is keeping quiet while hunting for a way to stop it first."],
  ["secret", "A small object taken on impulse long ago from someone the character has since come to love, which grows harder to return with every year."],
  ["secret", "Someone keeps up an appearance of comfortable wealth by selling heirlooms one at a time and replacing each with a copy, and is the only person who remembers which are real."],
  ["secret", "{Who} has quietly forgiven an old enemy and tells no one, because everyone else's loyalty depends on the grudge."],
  ["secret", "A child who has understood far more of the household's trouble than any adult suspects, and has begun to manage it."],
  ["secret", "The keeper of everyone else's confidences has nobody to give their own to, and the pressure has begun to leak out in odd, unguarded ways."],
  ["secret", "A person everyone assumes cannot follow the local language, who has understood every private conversation held in front of them."],

  // ── relationship ───────────────────────────────────────────────────────────
  ["relationship", "Two rivals who, without ever saying so, have built their lives around each other's next move, and the day one of them stops playing."],
  ["relationship", "A mentor and a student where the student has overtaken the teacher, and both keep performing the old arrangement because neither knows who they are without it."],
  ["relationship", "Siblings who each believe they were the overlooked one, each holding childhood evidence that proves it, and who are both right."],
  ["relationship", "{Who} has a friend they love and no longer like, and every visit becomes a negotiation between the two feelings."],
  ["relationship", "A pair who are each the only witness to the other's worst day, which makes leaving feel like abandoning the sole keeper of the truth."],
  ["relationship", "A parent and a grown child who communicate almost entirely through chores, favours, and practical help, because direct words would break something fragile."],
  ["relationship", "The one person who really understands {who} is the adversary, which makes every confrontation the most intimate conversation either of them has all year."],
  ["relationship", "Two people who have only ever met with a third person in the room, and are about to be left alone together for the first time."],
  ["relationship", "A friendship that thrives in one narrow place, a train carriage, a club, a rooftop, and collapses whenever it is carried into ordinary life."],
  ["relationship", "A caretaker and the person being cared for, where the real power runs in the opposite direction to what the arrangement suggests."],
  ["relationship", "Someone in love with a person who belongs to everyone, a leader, a performer, a healer, who has to decide whether being one of the crowd is enough."],
  ["relationship", "Three friends whose group works only because one of them is constantly translating the other two to each other, and that one is tired."],
  ["relationship", "The longest-serving person in {place} and {who} each know the real story of something that happened there, and each assumes the other has forgotten it."],
  ["relationship", "Two colleagues who have each believed for years that they are the one holding the whole place up."],
  ["relationship", "Neighbours who have shared a wall for years and know each other's habits intimately through sound alone, though they have never exchanged more than a nod."],

  // ── history ────────────────────────────────────────────────────────────────
  ["history", "A first language that almost no one around the character speaks now, though it still surfaces when they count, swear, or are frightened, and nobody has ever asked about it."],
  ["history", "A childhood home run on rules nobody explained, and a grown-up character who still obeys a few of them without knowing why."],
  ["history", "A serious illness years ago that everyone has politely stopped mentioning, so the character's caution is read as temperament by anyone who never knew the before."],
  ["history", "{Who} grew up with a family legend retold at every gathering, and has just learned which part of it was always left out."],
  ["history", "Years spent as the full-time carer of someone who has since died, leaving the character with hard-won expertise, a rigid daily routine, and no one left to need either."],
  ["history", "Raised in part by an older sibling who was barely more than a child themself, a character who still hears that sibling's rules as the voice of authority."],
  ["history", "Someone once took the character in during a bad winter, and the character has spent years repaying that kindness in strange, escalating ways."],
  ["history", "{Who} once did something that one community called unforgivable and another called heroic, and has learned which reputation to wear depending on whose door they are standing at."],
  ["history", "Years of formal training in a field the character was never allowed to practise, whose skills leak out in odd, specific, slightly embarrassing ways."],
  ["history", "A family where everyone did the same work for generations, and a character whose boldest act of rebellion was to be deliberately mediocre at the family trade."],
  ["history", "An apprenticeship under a frightening mentor, whose habits the character catches themselves repeating, down to the way a door gets closed."],
  ["history", "Someone who has told the story of the worst day of their life so many times, to so many audiences, that it has worn smooth and no longer touches what actually happened."],
  ["history", "Someone in {place} knows what {who} used to be, and has been waiting patiently for the right moment to mention it."],
  ["history", "A single event in the past taught the character most of what they believe about {theme}, though they have never connected the two."],
  ["history", "A childhood spent as the go-between in a long family estrangement, carrying messages between people who were not speaking, and a grown-up who still senses at once who in any room needs managing."],

  // ── quirk ──────────────────────────────────────────────────────────────────
  ["quirk", "Counting small things, stairs or ceiling tiles or the buttons on a coat, but only when hiding something, so a patient observer could learn to read the tell."],
  ["quirk", "Someone who gives every household object a rank and a title, and is genuinely distressed when the kettle is promoted without consultation."],
  ["quirk", "A habit of rehearsing every important conversation aloud in an empty room, and being visibly thrown when the real person goes off the planned course."],
  ["quirk", "Someone who refuses to use a person's name until they have decided to trust them, so the cast can be ranked by who is still addressed by title or not at all."],
  ["quirk", "A way of talking borrowed from one old trade, sailing or farming or banking, applied to everything from romance to grief."],
  ["quirk", "{Who} cannot walk past a stray button, coin, or key without pocketing it, and keeps a drawer of lost things waiting for their owners."],
  ["quirk", "A ritual that looks like superstition from outside and pure practicality from inside, learned on a day the character never discusses."],
  ["quirk", "Someone who lies far better when their hands are busy, and so mends, shuffles, or washes up whenever they need to be believed."],
  ["quirk", "{Who} hums the same tune when anxious, and anyone who notices can judge exactly how bad things are by how far through it the humming gets."],
  ["quirk", "A conversational tic of repeating each question back word for word before answering, which buys time and has been mistaken for thoughtfulness."],
  ["quirk", "A character who keeps every clock deliberately wrong, and whose private arithmetic for correcting them says a lot about what they fear being late for."],
  ["quirk", "A mage who cannot cast anything without first tidying the nearest surface, and who treats the clutter on other people's tables as a personal insult."],
  ["quirk", "{Who} takes the same route through {place} every day, with the same pauses, and the one day it changes tells everybody something is wrong."],
  ["quirk", "Someone who cannot sleep without one specific mundane noise, a dripping tap or a radio between stations, and whose life has organised itself around where that noise is available."],

  // ── arc ────────────────────────────────────────────────────────────────────
  ["arc", "A change measured entirely in what the character stops doing, a habit dropped, a topic no longer avoided, a call finally returned, with no single moment to point to."],
  ["arc", "An arc that runs backwards: a warm, open character hardened by what the story does to them, with the reader feeling it as a loss rather than a victory."],
  ["arc", "{Who} rebuilds everything visible, new city, new work, new friends, and carries the original problem across intact, like luggage nobody thought to open."],
  ["arc", "The same chance to change, offered again and again and declined in smaller and quieter ways each time, until the last refusal costs the most."],
  ["arc", "{Who} learns a lesson that feels like growth and is actually a tidier version of the original mistake."],
  ["arc", "An arc driven by repetition rather than epiphany: a character becomes who they need to be by performing one small, difficult act until it finally holds."],
  ["arc", "Someone who needs to become less admirable to become more human, and must be seen failing badly and in public."],
  ["arc", "{Who} begins as the person who handles everyone else's trouble and ends by letting someone else handle a problem of their own."],
  ["arc", "A change that everyone around the character can see except the character, who keeps insisting on the old self while others adjust around them."],
  ["arc", "A slow discovery, sometimes a happy one, that the person who started out sure they were the lead in everyone's story is a supporting player in several."],
  ["arc", "A redemption arc where the character is never forgiven and has to decide whether the change still counts without an audience."],
  ["arc", "A gradual corruption where every individual step is reasonable, and the reader keeps checking for the moment it went wrong."],
  ["arc", "An arc that tracks a changing relationship to {theme}, from avoiding it, to bargaining with it, to a truce neither side expected."],
  ["arc", "A character who begins the story already defeated, so the arc is not a fall but a slow, unwilling climb from a floor they had decided was permanent."],
  ["arc", "Exactly what the character wanted arrives early, and the rest of the story is the harder work of finding out who they are once the wanting is over."],
  ["arc", "The unchanging character in a changing world, whose steadiness starts out as the story's anchor and slowly becomes the thing everyone has to work around."],

  // ── foil ───────────────────────────────────────────────────────────────────
  ["foil", "A near-twin of the main character, with the same talent, training, and ambition plus one stroke of luck the main character never had, and no idea how much that single thing explains."],
  ["foil", "Someone who makes all the same choices as {who} for gentler reasons, exposing {who}'s motives without a single accusation."],
  ["foil", "A person plainly worse at the main character's skill and visibly happier for it, whose peace is an uncomfortable mirror."],
  ["foil", "A counterpart who took the safe road at the exact fork where the main character took the risky one, and the two are meeting again at the far end of their roads."],
  ["foil", "The other side of the same wound: two people hurt by one event, one turned to anger and one to forgiveness, each privately certain the other is in denial."],
  ["foil", "A newcomer who repeats {who}'s old mistakes with total confidence, forcing {who} to choose between interfering and letting history repeat."],
  ["foil", "A foil whose dishonesty is easy to forgive, so that the main character's more respectable dishonesty looks worse by comparison."],
  ["foil", "A comic foil whose cheerful incompetence means the main character never feels in competition with them, which makes this the most honest relationship in the story."],
  ["foil", "An antagonist who holds the main character's own principle one step further than they would dare, so every confrontation is a look at where that principle ends."],
  ["foil", "A foil defined by what they refuse to want: a person with no ambition in a room full of ambitious people, and therefore the only one nobody can bribe."],
  ["foil", "A foil who says the main character's unspoken thoughts aloud, shamelessly and often, and is both an embarrassment and a relief."],
  ["foil", "Someone who feels at home in {place} in a way {who} never has, and who has no idea how much that is resented."],
  ["foil", "Someone who personifies {theme} so completely that every conversation with them becomes a debate the main character never planned to have."],

  // ── question: things to answer about the person first ──────────────────────
  ["question", "What does {who} do on a day when nothing at all is required, and who, if anyone, ever sees it?"],
  ["question", "Which thing would this character never sacrifice, and who is the first to see that it has stopped being worth the price?"],
  ["question", "Who does this character turn to in a crisis, and why is it not the person they would name if asked?"],
  ["question", "What does {who} keep that should have been thrown out long ago, and who knows it is still there?"],
  ["question", "Where is this character confidently and consistently wrong, and who has been too kind to correct them?"],
  ["question", "Which of this character's best qualities was learned from someone they now refuse to forgive?"],
  ["question", "How would this character behave if everyone around them were completely honest for one afternoon?"],
  ["question", "When did this character last change their mind in front of someone, and what did it cost them?"],
  ["question", "Whose approval is this character still trying to earn, and does that person even know a contest is under way?"],
  ["question", "When this character holds a small piece of power, a door or a clipboard or a key, what do they do with it, and what does that reveal that a large one would hide?"],
  ["question", "Which belief does {who} fear is secretly true, and what elaborate arrangements keep it permanently untested?"],
  ["question", "How does this character react in the moment they are proved wrong, and who has learned to brace for it?"],
  ["question", "Which of this character's habits is secretly a response to {theme}, whether they know it or not?"],
  ["question", "What would the person who dislikes this character most say is their best quality, and would they be right?"],
  ["question", "How does this character behave in a room where they have no standing at all, and when did that last happen to them?"],
];
