// Idea bank: character. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
export default [
  // ── spark: a whole person in one breath ────────────────────────────────────
  ['spark', 'A lighthouse keeper whose beam guides no ships any more, because the shipping lanes moved long ago and no one has had the heart to tell the keeper.'],
  ['spark', 'Someone who spent a career being dangerous and now runs the lost-property office at a railway station, where the old instincts find oddly gentle uses.'],
  ['spark', 'A court interpreter who deliberately softens what each side says to the other, and is the only person who knows how fragile the peace between them really is.'],
  ['spark', 'Picture {who} as someone who keeps a bag by the door and a rehearsed plan for every disaster except the one that is actually coming.'],
  ['spark', 'A shipboard intelligence built to be unable to lie, whose crew has learned to ask only the questions they can bear the answers to.'],
  ['spark', 'A funeral caterer who can read a family\'s whole history from what the mourners reach for and what they quietly refuse.'],
  ['spark', 'Take the most forgettable background figure in your project, the one who only opens doors or delivers messages, and decide what ambition has been swallowed all this time.'],
  ['spark', 'A ghost bound not to a house or a death but to an unfinished argument, who cannot move on until a living person agrees to finish it.'],
  ['spark', 'Give {who} an inheritance that is a debt instead of a fortune, owed to someone who has waited patiently for exactly this generation.'],
  ['spark', 'An in-house apologiser for a powerful family, who has said sorry on everyone else\'s behalf for so long that the personal debts have gone uncounted.'],
  ['spark', 'A matchmaker who has never been in love and runs the most successful service in town by treating romance as logistics, until one client refuses to be optimised.'],
  ['spark', 'A hedge-witch whose only dependable talent is persuading unwelcome things to leave quietly, from damp and pests to ghosts and tax collectors.'],
  ['spark', '{Who} belongs so completely to {place} that being anywhere else produces a smaller, less certain version of the same person.'],
  ['spark', 'Someone whose private life is a quiet argument against {theme}, and who has no idea anyone has noticed.'],

  // ── want ───────────────────────────────────────────────────────────────────
  ['want', 'Someone wants to be forgiven by a person who does not even remember the offence, and has to decide whether reminding them counts as part of the apology.'],
  ['want', '{Who} wants to be left in peace, and the real test of that wish arrives the day everyone finally obliges.'],
  ['want', 'Try a want that is small and specific, a particular chair, a family recipe, a seat by the window, and notice how dangerous the smallness becomes when it is denied.'],
  ['want', '{Who} wants to win an old argument against someone who has since died, which means the opponent can no longer concede.'],
  ['want', 'Someone wants to disappear completely, but every workable plan for vanishing needs help from the one person who would be hurt most by it.'],
  ['want', 'Being needed is the whole want: a character who quietly arranges small emergencies so that people keep turning up at the door.'],
  ['want', 'A borrowed ambition, one that belonged to a parent or a lost sibling, has been chased so long that it has started to feel foreign to the person chasing it.'],
  ['want', 'Someone wants a second chance at something they once did badly, and it arrives in a form that is smaller, stranger, and far more humiliating than the original.'],
  ['want', '{Who} wants revenge and a place at the family table in equal measure, and every step toward the first closes a door to the second.'],
  ['want', '{Who} wants to be ordinary, and hiding a rare talent turns out to take far more effort than any heroic act would.'],
  ['want', 'A long-haul spacer wants nothing more than a small, boring house with a garden, and every well-paid contract takes that garden one star further out of reach.'],
  ['want', 'Someone whose deepest want is the exact opposite of {theme}, and who has not noticed that want steering every choice.'],
  ['want', '{Who} wants to leave {place} behind and has a dozen respectable reasons for staying that all turn out to be one reason.'],

  // ── flaw ───────────────────────────────────────────────────────────────────
  ['flaw', 'Generosity that is really control: every gift comes with an unspoken ledger, and the giver is baffled when people start avoiding their kindness.'],
  ['flaw', '{Who} cannot bear being thanked, and deflects, jokes, or leaves the room whenever gratitude is about to land, so people begin to feel their kindness was refused.'],
  ['flaw', 'Pride disguised as humility: someone who loudly volunteers for the worst job so that no one else can be seen doing it better.'],
  ['flaw', '{Who} has a gift for being right at precisely the wrong moment, delivering the accurate, unwelcome truth at the one time it can only wound.'],
  ['flaw', '{Who} treats every disagreement as a trial to be won, and keeps a running tally of old verdicts that nobody else knew were being scored.'],
  ['flaw', 'Someone so afraid of being a burden that they refuse all help, until the refusing becomes the heaviest thing the people around them have to carry.'],
  ['flaw', 'Cowardice that passes for patience: a character who waits for the perfect moment so skilfully that it never arrives.'],
  ['flaw', 'A talent for charm that has never had to be sincere, so when sincerity is finally required there is no practised version of it to reach for.'],
  ['flaw', '{Who} cannot tolerate not knowing, and will open the letter, the door, or the sealed box even when everything suggests the not-knowing was the protection.'],
  ['flaw', 'A character who edits the past so lovingly that no present person, place, or chance can ever measure up to it.'],
  ['flaw', 'Someone who answers every serious moment with a joke, and who will eventually meet the one person patient enough to stop laughing and simply wait.'],
  ['flaw', 'A hero who cannot refuse a quest, any quest, from any stranger, and has never once asked who stands to benefit.'],
  ['flaw', 'A habit of hoarding apologies, favours, and grievances alike and never spending any of them, until the account is too large to settle.'],
  ['flaw', '{Who} guards {place} as though it were a person, treating any change to it, however small, as a personal betrayal.'],

  // ── contradiction ──────────────────────────────────────────────────────────
  ['contradiction', 'Someone who stays calm in a genuine emergency and comes apart over small social embarrassments, like a forgotten name or a misjudged greeting.'],
  ['contradiction', 'A devoted rule-keeper whose one carefully guarded exception happens to be the rule everyone else depends on most.'],
  ['contradiction', '{Who} is famous for honesty and maintains a single lie so carefully that it has become the load-bearing wall of an otherwise truthful life.'],
  ['contradiction', 'A person who is harsh with the people they love and tender with strangers, because strangers have not yet had the chance to disappoint them.'],
  ['contradiction', 'A devout believer who no longer feels anything in worship and keeps showing up out of loyalty to the person they used to be.'],
  ['contradiction', 'A ruthless strategist who can plan a whole campaign in an afternoon and loses an hour choosing what to have for lunch.'],
  ['contradiction', 'A character who performs for crowds with total ease and cannot hold a one-to-one conversation for more than a few minutes without hunting for an exit.'],
  ['contradiction', '{Who} is trusted by everyone and trusts no one, and has built an entire reputation on the gap between the two.'],
  ['contradiction', 'An optimist whose cheerfulness is a daily discipline rather than a temperament, upheld at visible cost and starting to slip.'],
  ['contradiction', 'A famously lazy person who works tirelessly on one hidden project, with the public idleness serving as camouflage.'],
  ['contradiction', 'A character who scorns sentimentality and keeps every scrap of evidence of the people they have loved, sorted and labelled in a place they never open.'],
  ['contradiction', 'A feared warlord who keeps bees and becomes gentle to the point of ceremony around the hives.'],
  ['contradiction', '{Who} complains constantly about {place} and would be quietly devastated by being sent anywhere else.'],

  // ── secret ─────────────────────────────────────────────────────────────────
  ['secret', 'A character quietly pays for something, a stranger\'s medical bills or a neglected grave, and would be mortified if the kindness were ever discovered.'],
  ['secret', '{Who} knows how the event everyone in town tells differently actually ended, and has let the tidier version stand to protect someone.'],
  ['secret', 'A second identity in the next town over, kinder and braver than the first, and the real trouble is that the invented self is the better person.'],
  ['secret', 'Make the secret fragile rather than shameful: a private joy, hobby, or love that the character guards because the world would flatten it into something ordinary.'],
  ['secret', '{Who} is hiding that a great talent has gone, and every public performance has become an elaborate, careful act of remembering.'],
  ['secret', '{Who} is keeping a promise that nobody remembers extracting, made to a person who can no longer release {who} from it.'],
  ['secret', 'A small, ordinary stolen object that a character has kept for years, and that grows harder to return with every season it stays hidden.'],
  ['secret', 'A character lives under the name of someone who died, and the dead person\'s relatives keep sending cards to an address they were never supposed to find.'],
  ['secret', '{Who} has quietly forgiven an old enemy and tells no one, because everyone else\'s loyalty depends on the grudge.'],
  ['secret', 'A secret fear of something absurd, a certain sound, a colour, a kind of weather, and an entire personality built around avoiding it.'],
  ['secret', 'The keeper of everyone else\'s confidences has nobody to give their own to, and the pressure has begun to leak out in odd, unguarded ways.'],
  ['secret', 'A servant who taught themselves to read from discarded papers, and who therefore knows exactly what the household is hiding and that nobody believes it possible.'],

  // ── relationship ───────────────────────────────────────────────────────────
  ['relationship', 'Pair two rivals who, without ever saying so, have built their lives around each other\'s next move, then ask what happens when one of them quietly stops playing.'],
  ['relationship', 'A mentor and a student where the student has quietly overtaken the teacher, and both keep performing the old arrangement because neither knows who they are without it.'],
  ['relationship', 'Siblings who each believe they were the overlooked one, each holding childhood evidence that proves it, and who are both right.'],
  ['relationship', '{Who} has a friend they love and no longer like, and every visit becomes a negotiation between the two feelings.'],
  ['relationship', 'A pair who are each the only witness to the other\'s worst day, which makes leaving feel like abandoning the sole keeper of the truth.'],
  ['relationship', 'A parent and a grown child who communicate almost entirely through chores, favours, and practical help, because direct words would break something fragile.'],
  ['relationship', 'The one person who really understands {who} is the adversary, which makes every confrontation the most intimate conversation either of them has all year.'],
  ['relationship', 'Two people who were once inseparable and now share only a long, specific silence, each waiting for the other to be first to name what happened.'],
  ['relationship', 'A friendship that thrives in one narrow place, a train carriage, a club, a rooftop, and collapses whenever it is carried into ordinary life.'],
  ['relationship', 'A caretaker and the person being cared for, where the real power runs in the opposite direction to what the arrangement suggests.'],
  ['relationship', 'Someone in love with a person who belongs to everyone, a leader, a performer, a healer, who has to decide whether being one of the crowd is enough.'],
  ['relationship', 'Two people bound by a contract, a bet, or a borrowed disguise, each privately wondering when the arrangement stopped being the part they were pretending about.'],
  ['relationship', 'The longest-serving person in {place} and {who} share an unspoken understanding about something that happened there, and neither has ever brought it up.'],

  // ── history ────────────────────────────────────────────────────────────────
  ['history', 'Someone who was once a very different, far better-known person, whose quiet current life is a deliberate, hard-won undoing of that earlier fame.'],
  ['history', 'A childhood home run on rules nobody explained, and a grown-up character who still obeys a few of them without knowing why.'],
  ['history', 'An early betrayal by a close friend, at the age when friendships felt permanent, which has quietly shaped every adult relationship since.'],
  ['history', '{Who} grew up with a family legend retold at every gathering, and has just learned which part of it was always left out.'],
  ['history', 'A character who moved so often as a child that belongings are always carried and never placed, and a permanent address feels like a trap.'],
  ['history', 'Try an early success that peaked too young, leaving the character to measure every later effort against a version of themselves that no longer exists.'],
  ['history', 'Someone once took the character in during a bad winter, and the character has spent years repaying that kindness in strange, escalating ways.'],
  ['history', '{Who} once did something that one community called unforgivable and another called heroic, and still answers to both reputations depending on whose door is knocked on.'],
  ['history', 'Years of formal training in a field the character was never allowed to practise, whose skills leak out in odd, specific, slightly embarrassing ways.'],
  ['history', 'A family where everyone did the same work for generations, and a character whose boldest act of rebellion was to be deliberately mediocre at the family trade.'],
  ['history', 'An apprenticeship under a frightening mentor, whose habits the character catches themselves repeating, down to the way a door gets closed.'],
  ['history', 'A child of a generation ship who has just learned the voyage is nearly over, and for whom arrival means the end of the only world there has ever been.'],
  ['history', 'Someone in {place} knows what {who} used to be, and has been waiting patiently for the right moment to mention it.'],
  ['history', 'A single event in the past taught the character most of what they believe about {theme}, though they have never connected the two.'],

  // ── quirk ──────────────────────────────────────────────────────────────────
  ['quirk', 'A character who counts small things, stairs or ceiling tiles or the buttons on a coat, only when something is being hidden, so a patient observer could learn to read it.'],
  ['quirk', 'Someone who gives every household object a rank and a title, and is genuinely distressed when the kettle is promoted without consultation.'],
  ['quirk', 'A character who rehearses every important conversation aloud in an empty room, and is visibly thrown when the real person goes off the planned course.'],
  ['quirk', '{Who} always sits where the exits are visible, and has a dozen innocent explanations, none of which convinces anyone.'],
  ['quirk', 'A way of talking borrowed from one old trade, sailing or farming or banking, applied to everything from romance to grief.'],
  ['quirk', '{Who} cannot walk past a stray button, coin, or key without pocketing it, and keeps a drawer of lost things waiting for their owners.'],
  ['quirk', 'A ritual that looks like superstition from outside and pure practicality from inside, learned on a day the character never discusses.'],
  ['quirk', 'Someone who never fully unpacks, and whose half-open suitcase is a running commentary on how safe they feel anywhere.'],
  ['quirk', '{Who} hums the same tune when anxious, and anyone who notices can judge exactly how bad things are by how far through it the humming gets.'],
  ['quirk', 'A relentlessly polite character with one specific trigger that makes all the manners vanish at once.'],
  ['quirk', 'A character who keeps every clock deliberately wrong, and whose private arithmetic for correcting them says a lot about what they fear being late for.'],
  ['quirk', 'A mage who cannot cast anything without first tidying the nearest surface, and who treats the clutter on other people\'s tables as a personal insult.'],
  ['quirk', '{Who} takes the same unchanging route through {place}, with the same pauses, and the one day it changes tells everybody something is wrong.'],

  // ── arc ────────────────────────────────────────────────────────────────────
  ['arc', 'A slow, believable surrender of a belief the character has defended for years, with each small concession making the next one easier to live with.'],
  ['arc', 'An arc that runs backwards: a warm, open character hardened by what the story does to them, with the reader feeling it as a loss rather than a victory.'],
  ['arc', '{Who} transforms in every visible way except the one that matters, and the gap between the two is the quiet tragedy.'],
  ['arc', 'A character offered the same chance to change again and again, who declines in smaller and quieter ways each time, until the last refusal costs the most.'],
  ['arc', '{Who} learns a lesson that feels like growth and is actually a tidier version of the original mistake.'],
  ['arc', 'An arc driven by repetition rather than epiphany: a character becomes who they need to be by performing one small, difficult act until it finally holds.'],
  ['arc', 'Someone who needs to become less admirable to become more human, and must be seen failing badly and in public.'],
  ['arc', '{Who} begins as the person who handles everyone else\'s trouble and ends by letting someone else handle a problem of their own.'],
  ['arc', 'A change that everyone around the character can see except the character, who keeps insisting on the old self while others quietly adjust.'],
  ['arc', 'A character spends the whole story preparing to be brave, and the real change is discovering that readiness was never going to arrive.'],
  ['arc', 'A redemption arc where the character is never forgiven and has to decide whether the change still counts without an audience.'],
  ['arc', 'A gradual corruption where every individual step is reasonable, and the reader keeps checking for the moment it went wrong.'],
  ['arc', 'Let the arc be a private argument with {theme}: lost early, won late, or conceded with surprising grace.'],

  // ── foil ───────────────────────────────────────────────────────────────────
  ['foil', 'Try a foil who has everything the main character wants and is quietly miserable, so that envy and pity have to be held at once.'],
  ['foil', 'A foil who makes all the same choices as {who} for gentler reasons, exposing {who}\'s motives without a single accusation.'],
  ['foil', 'A foil plainly worse at the main character\'s skill and visibly happier for it, whose peace is an uncomfortable mirror.'],
  ['foil', 'A foil who took the safe road at the exact fork where the main character took the risky one, and the two are meeting again at the far end of their roads.'],
  ['foil', 'A foil from the other side of the same wound: both hurt by one event, one turned to anger and one to forgiveness, and each privately believes the other is in denial.'],
  ['foil', 'A newcomer who repeats {who}\'s old mistakes with total confidence, forcing {who} to choose between interfering and letting history repeat.'],
  ['foil', 'A foil whose dishonesty is easy to forgive, so that the main character\'s more respectable dishonesty looks worse by comparison.'],
  ['foil', 'A comic foil whose cheerful incompetence is the one steady thing in a world falling apart, and the only person the main character never feels on guard around.'],
  ['foil', 'An antagonist who believes exactly what the main character believes, but one step further, a mirror showing where the principle ends if it is followed all the way.'],
  ['foil', 'A foil defined by what they refuse to want: a person with no ambition in a room full of ambitious people, and therefore the only one nobody can bribe.'],
  ['foil', 'A foil who says the main character\'s unspoken thoughts aloud, shamelessly and often, and is both an embarrassment and a relief.'],
  ['foil', 'Someone who feels at home in {place} in a way {who} never has, and who has no idea how much that is resented.'],
  ['foil', 'A foil who embodies {theme} so completely that the main character has to argue with it face to face.'],

  // ── question: things to answer about the person first ──────────────────────
  ['question', 'What does {who} do on a day when nothing at all is required, and who, if anyone, ever sees it?'],
  ['question', 'What is the last thing this character would ever sacrifice, and who would be the first to point out it is not worth keeping?'],
  ['question', 'Who does this character turn to in a crisis, and why is it not the person they would name if asked?'],
  ['question', 'What does {who} keep that should have been thrown out long ago, and who knows it is still there?'],
  ['question', 'What is this character confidently and consistently wrong about, and who has been too kind to correct them?'],
  ['question', 'Which of this character\'s best qualities was learned from someone they now refuse to forgive?'],
  ['question', 'How would this character behave if everyone around them were completely honest for one afternoon?'],
  ['question', 'Which flattering belief does {who} hold about their own life that the people closest quietly leave undisturbed?'],
  ['question', 'Whose approval is this character still trying to earn, and does that person even know a contest is under way?'],
  ['question', 'What does this character do with a small piece of power, holding a door or a clipboard or a key, and what does that reveal that a large one would hide?'],
  ['question', 'What does {who} fear is secretly true, and what elaborate arrangements keep it permanently untested?'],
  ['question', 'What would it take for this character to ask for help, and who is the one person they would choose?'],
  ['question', 'Which of this character\'s habits is secretly a response to {theme}, whether they know it or not?'],
];
