// Idea bank: essay. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
// Strings use double quotes so apostrophes read naturally; the text itself never contains quotation marks.
export default [
  // ── spark ───────────────────────────────────────────────────────────────────
  ['spark', "An essay shaped like a long apology to someone who never asked for one, slowly revealing that the person who needed it most is the one offering it."],
  ['spark', "A piece about the object your family argued over politely for years, until the politeness itself becomes the real subject."],
  ['spark', "Take a skill you were praised for as a child and ask, kindly but without mercy, who the praise was really for."],
  ['spark', "Two versions of the same year, one from the family story and one from whatever is left in the drawer, with the essay living in the gap between them."],
  ['spark', "A small, unflattering admission about {topic} that you have been editing out of conversations for years, given the whole essay instead of a throwaway aside."],
  ['spark', "An essay about something you got good at by accident, and the odd grief of realising the accident was the best part."],
  ['spark', "A love letter to a bad habit, honest enough that the habit starts to look like a loyal friend and a slow thief at the same time."],
  ['spark', "Take the most boring day of your childhood and treat it as the hinge, asking what was quietly decided that afternoon while nobody was looking."],
  ['spark', "{Theme}, approached through one repeated chore, the way you might come to understand a whole country by watching a single market stall."],
  ['spark', "An essay built as a list of everything you used to believe about {topic}, ordered so each correction costs a little more than the last."],
  ['spark', "A memoir piece about the version of you who existed for one summer only, and what that stranger would make of your life now."],
  ['spark', "What {place} knew about your family before you did, and what it has quietly kept to itself ever since."],

  // ── angle ───────────────────────────────────────────────────────────────────
  ['angle', "Come at {topic} through the people who were in the room but never in the story, the ones your family retells as scenery."],
  ['angle', "The late-arrival angle: you meet the subject after everything important has happened, with only leftovers, rumours and half-kept objects to reason from."],
  ['angle', "The angle of being wrong in real time, with the narrator refusing to pretend the wisdom of hindsight was available back then."],
  ['angle', "Treat your own memory as the shaky witness in a trial, and let the piece become an honest cross-examination of what you think you know about {topic}."],
  ['angle', "Approach a huge feeling by way of its smallest logistics: the timetables, the paperwork, the exact cost of getting somewhere you did not want to go."],
  ['angle', "Choose the angle that makes you a minor character in your own story, with someone else's decision at the centre and you watching from the edge."],
  ['angle', "Come in through a trade or a practical craft you learned alongside the thing that hurt, so grief arrives disguised as expertise."],
  ['angle', "What if the essay is not about what happened but about who has been allowed to tell it since, and who got corrected?"],
  ['angle', "A comic angle on {topic}, honest enough that the humour becomes a way of paying attention rather than a way of leaving."],
  ['angle', "{Theme} seen from the opposite seat: the person who caused it, witnessed it or benefited from it, given a fair hearing by someone with every reason not to."],
  ['angle', "The angle of the inheritor: what did you receive from the people before you that you never asked for, never use and cannot throw away?"],
  ['angle', "Treat {place} as a participant rather than a backdrop, with its own habits, grudges and way of deciding who gets to stay."],

  // ── hook ────────────────────────────────────────────────────────────────────
  ['hook', "Open in the middle of an argument, right at the exchange that mattered, and let the reader catch up on who is arguing and why."],
  ['hook', "Begin with a rule your family followed without ever stating it, and let the first crack in that rule become the reason for the essay."],
  ['hook', "Start with the smallest object that survived and make the reader wonder exactly what it survived."],
  ['hook', "Lead with a small confession, light enough to be funny and specific enough that the reader senses it is the thin end of something larger."],
  ['hook', "Open on the moment after, in the quiet where nobody knows what to do with their hands, and go back for the cause later."],
  ['hook', "Begin with something you only learned as an adult about {place}, somewhere you thought you knew completely, so the whole past tilts slightly."],
  ['hook', "Open with a misunderstanding you held for years so confidently that the reader holds it too, until the piece gently takes it away."],
  ['hook', "Use a prohibition as the hook: a room, a drawer, a road or a topic you were told never to approach, and the lure of finally going near it."],
  ['hook', "Begin with {topic} in its most ordinary form, an unremarkable weekday version, so the strangeness has to arrive on its own."],
  ['hook', "Open on a question a child once asked you that you could not answer, and let the essay be a very late reply."],
  ['hook', "Promise one story, a holiday or a wedding or a move, while keeping the real story in the corner of the frame until the reader leans toward it."],
  ['hook', "Open on {place} at an hour when nobody is meant to be there, so the reader arrives as a trespasser rather than a guest."],
  ['hook', "Begin with the smallest physical sign of {theme} you ever noticed in someone else, before you understood it was also in you."],

  // ── thread ──────────────────────────────────────────────────────────────────
  ['thread', "Follow a single recurring object, a coat or a key or a chipped bowl, as it changes hands or meaning each time it reappears and traces the family through its journey."],
  ['thread', "Ask the same question at every stage of life and let it earn a different answer each time, the answers adding up to a portrait of how you changed."],
  ['thread', "A through-line of thresholds: every section catches you on one, going in or out or lingering, and what the doorway asks of you shifts each time."],
  ['thread', "Let {theme} be the thread but never the word, appearing only through behaviour, in the things people do when they believe nobody is counting."],
  ['thread', "Let weather or light or the season carry the emotional temperature, so the narrator never has to announce it."],
  ['thread', "Inherited sayings that moved through your family unchecked, each one examined for who first needed it to be true."],
  ['thread', "Trace a skill that gets passed down badly, with every lesson teaching something other than what it was meant to teach."],
  ['thread', "One unanswered letter, call or message as the hanging thread, each section approaching it from closer in and flinching at a different distance."],
  ['thread', "Money as the quiet through-line: who paid, who owed, who pretended not to keep count, read as a language of love and of leverage at once."],
  ['thread', "A pattern of departures, each a different kind of leaving, until the reader sees what you were running toward all along."],
  ['thread', "Treat {topic} as an apprenticeship, with each part showing you being taught by someone who had no idea they were teaching."],
  ['thread', "Let {place} change slowly from section to section, its repairs, closures and rearranged furniture marking time better than any date could."],
  ['thread', "Follow {topic} across the different ages you met it, so the through-line is you growing into a question instead of an answer."],

  // ── structure ───────────────────────────────────────────────────────────────
  ['structure', "A braided essay with two strands, an old story and a current question, alternating until the strands begin to answer each other."],
  ['structure', "Organise it as a walk through the rooms of one house, in an order that is emotional rather than architectural."],
  ['structure', "Break it into very short sections where the white space between them does as much work as the sections themselves."],
  ['structure', "Reverse chronology: start where things ended up and move backward until the reader understands why the opening felt so quiet."],
  ['structure', "One long scene held almost still, with digressions that each carry a different decade into the room and then leave again."],
  ['structure', "Build it as an inventory of objects, each entry quietly widening from the thing into the person who owned it."],
  ['structure', "Show a before and an after and leave out the middle, letting the reader build the bridge you cannot bear to look at."],
  ['structure', "Alternate between what you remember and what the records say, giving each its own texture, so the disagreement itself becomes the plot."],
  ['structure', "Hang the piece on a recipe, a route or a set of instructions, where the steps are the skeleton and the life leaks out between them."],
  ['structure', "Make the shape deliberately lopsided: one long, loving stretch about something trivial, then a single very short section about the thing that mattered."],
  ['structure', "Circle the central event without entering it, each section arriving from a different side and a different year, until the reader can see its outline."],
  ['structure', "Let the order follow what has been built, broken and rebuilt in {place}, with you appearing only where the changes touched your life."],
  ['structure', "Let {topic} arrive only in the final section, after everything before it has quietly cleared the ground."],

  // ── turn ────────────────────────────────────────────────────────────────────
  ['turn', "The turn where you realise the person you resented was doing exactly what you now do, for a reason you are only now old enough to hear."],
  ['turn', "Halfway through, the essay admits that its own framing was a way of staying comfortable, and the turn is the cost of that admission."],
  ['turn', "The moment the question changes: you thought you were asking why it happened and you were really asking why you needed it to have happened that way."],
  ['turn', "Build the turn from a tiny fact, a date or a receipt or a mispronounced name, that quietly overturns the story you have told for years."],
  ['turn', "Let the turn come from outside: a stranger's offhand remark, an overheard conversation or a child's literal reading that reorders what you thought about {topic}."],
  ['turn', "Turn toward generosity: let the accusation soften into understanding without absolving anyone of anything."],
  ['turn', "A turn in the opposite direction: you begin by seeking forgiveness and end by discovering you were never the one who needed to ask."],
  ['turn', "The discovery that what you were mourning was never the loss itself but the version of yourself that would have existed otherwise."],
  ['turn', "An insight about {theme} that the evidence reluctantly supports but you would rather not hold, with the essay honest about how unwelcome it is."],
  ['turn', "A turn where the narrator stops explaining and simply notices, the voice going quiet and concrete exactly where the argument would normally speak up."],
  ['turn', "The point where the story you inherited and the story you lived stop being compatible, and you have to choose which one the essay keeps."],
  ['turn', "The moment you notice that {who} was frightened too, and every earlier scene needs to be seen again with that fact standing in it."],
  ['turn', "The turn that comes when you return to {place} and it is smaller, kinder or simply different from the memory you have been arguing from."],

  // ── scene ───────────────────────────────────────────────────────────────────
  ['scene', "The last time you were completely certain about something that turned out to be wrong, and who was standing nearby when it stopped being true."],
  ['scene', "A meal where the food was fine and everything around it was not: who sat where, who left early, who stayed behind to wash up."],
  ['scene', "The first time you saw a grown-up unsure what to do, and how that quietly rearranged your idea of who was in charge."],
  ['scene', "A car journey with someone who could only say what they meant when both of you were facing forward."],
  ['scene', "The room you were told to stay out of, and either the day you went in or the day you finally understood why."],
  ['scene', "A moment of being good at something in front of the person whose approval you were quietly working for, and what their face did."],
  ['scene', "The ordinary, unremarkable day before something ended, which you only recognised as the last of its kind much later."],
  ['scene', "A small, specific act of kindness you received and were too proud to acknowledge, from someone who may never know."],
  ['scene', "A hiding place in {place}, and everything you could hear, smell and misunderstand from inside it."],
  ['scene', "A job you hated, were too young for or loved more than made sense, and the particular people it put you beside."],
  ['scene', "A time you were being measured, interviewed, tested or judged, and what your hands were doing while you waited."],
  ['scene', "A phone call that ran longer than either of you intended, the point of it arriving only in the last stretch of silence."],
  ['scene', "The one memory of {who} that does not fit the version everyone else tells, and why you have kept it to yourself."],
  ['scene', "The first time you noticed {topic}, before you had a name for it, and who happened to be with you."],
  ['scene', "Something that happened in {place} that nobody has mentioned since, and what the silence has been holding up."],

  // ── tension ─────────────────────────────────────────────────────────────────
  ['tension', "The pull between loyalty to the people in the story and loyalty to the truth about them, with no clean way to honour both."],
  ['tension', "Let the narrator still love the thing being criticised, so every judgement visibly costs something and the reader can see the price."],
  ['tension', "The gap between what you felt then and what you are allowed to feel now, with the essay refusing to settle the argument in favour of either."],
  ['tension', "A fact you are not sure you have the right to tell because it belongs to someone else, and an essay honest about that hesitation."],
  ['tension', "Let {theme} pull in two directions at once: the version that comforts you against the version that actually explains what happened."],
  ['tension', "The suspicion that your best material is also your most convenient material, and that the story you tell well may be the one that lets you skip another."],
  ['tension', "A narrator who keeps reaching for the lesson and being stopped by details that refuse to cooperate."],
  ['tension', "Two people who remember the same event in incompatible ways, and you, who loved both of them, declining to play judge."],
  ['tension', "The essay's quiet fear: that the story only works if you are slightly kinder to yourself than you deserve, and the reader will sense it."],
  ['tension', "Gratitude and anger toward the same person, allowed to sit side by side on the page without either one getting the final word."],
  ['tension', "A ticking clock inside the material, a person or a house or a story about to be gone, so every section feels the weight of what has not yet been asked."],
  ['tension', "Let {who} be right about one thing you have spent the whole essay resisting, and notice how everything around it tightens."],
  ['tension', "Everything you want to say about {topic} against everything you can say without hurting someone, with the essay standing in the narrow space between."],
  ['tension', "{Place} as somewhere you are fond of and ashamed of in equal measure, with the essay refusing to flatter either feeling."],

  // ── ending ──────────────────────────────────────────────────────────────────
  ['ending', "End one beat before the answer, on the image that makes the answer obvious, and trust the reader to finish the thought."],
  ['ending', "Return to the opening object or room, unchanged, so the only thing that has moved is what the reader now sees in it."],
  ['ending', "Keep the ending deliberately small, a chore or a cup of tea or a door left unlocked, with the larger feeling just outside the frame."],
  ['ending', "Close on a question you cannot answer yet, honest rather than coy, addressed to the person it most concerns even if they will never read it."],
  ['ending', "Finish with a gesture that completes something the story kept interrupting: a delayed apology, a returned object, a meal finally eaten to the end."],
  ['ending', "Hand the last word to someone else's point of view, one detail from the other side that the narrator can only guess at."],
  ['ending', "Refuse the neat lesson: name the moral you were tempted to end on and say plainly why the material will not carry it."],
  ['ending', "Let {theme} close the piece not as a conclusion but as a present-tense condition, still going on, with no resolution promised."],
  ['ending', "End with the practical next step you actually took, small and unglamorous, instead of the emotional summit the reader expects."],
  ['ending', "Close by widening, a single glance from the private story toward everyone who has stood in a similar doorway, held lightly and never pushed."],
  ['ending', "Echo the shape of the opening in a different register, so the same structure now carries a very different weight."],
  ['ending', "Leave {place} for the last time carrying one small, unglamorous thing from it, with no comment on why."],
  ['ending', "A last image that quietly shifts the weight of {topic} without anyone in the piece commenting on it."],

  // ── title ───────────────────────────────────────────────────────────────────
  ['title', "Name the humblest object in the essay in the title, so the reader's first meeting with the piece is something they could hold."],
  ['title', "Let the title be a plain answer to the question the essay spends its whole length asking, giving away the destination and keeping the route."],
  ['title', "Borrow a phrase your family used for something it refused to name directly, so the title itself carries the avoidance."],
  ['title', "A title that makes a small, believable promise and then quietly breaks it, so the essay feels like a detour that turned out to be the road."],
  ['title', "Build a title from a place and an emotion, then test it by asking whether it would still be true if the place were swapped for another."],
  ['title', "A title that sounds like a label or a practical instruction, with the emotional weight arriving only on a second reading."],
  ['title', "A two-part title where the second half contradicts the tone of the first, mirroring the essay's own divided feeling."],
  ['title', "A title that is the least dramatic true thing you can say about {topic}, trusting understatement to do the work."],
  ['title', "A title that names the person absent from the essay, so the reader feels the shape of the missing before meeting anyone else."],
  ['title', "A title that is an ordinary time of day or season, small and exact, which the essay then slowly turns into an emotional location."],
  ['title', "A title taken from a mistake, a mishearing or a child's version of a word, later revealed as the truest thing in the piece."],
  ['title', "A title that names {place} not by what it is but by what people used it for, with the essay gradually explaining why."],
  ['title', "A title that circles {theme} without naming it, using the plainest nearby object as a stand-in."],

  // ── question ────────────────────────────────────────────────────────────────
  ['question', "What do you know now that you could not have known then, and how exactly did you come to know it?"],
  ['question', "Who in this story would read the finished piece most closely, and what would they be hunting for?"],
  ['question', "What is the one thing you are unwilling to say here, and does the essay quietly depend on it?"],
  ['question', "Is this essay about what happened, about what it meant, or about what you have done with it since?"],
  ['question', "What would you have to leave out for the story to be fair to everyone in it, and can you live with the gap?"],
  ['question', "Which parts of this are you telling because they are true, and which because they make you look the way you want to look?"],
  ['question', "What is {theme} doing in this piece: explaining the events, excusing them, or asking to be questioned by them?"],
  ['question', "If a stranger read only the middle of the piece, what would they think it was about, and would that be fair?"],
  ['question', "Whose permission, if anyone's, do you need to tell this, and what happens to the piece if you never get it?"],
  ['question', "What is the smallest true detail you remember about this, and what does it stubbornly refuse to explain?"],
  ['question', "Why this story now, and what changed in you that made it tellable, or impossible to keep untold?"],
  ['question', "When {topic} first mattered to you, what were you afraid of losing, and has that fear turned out to be the right one?"],
  ['question', "What does {who} want from this essay that you are not prepared to give, and what do you want from them?"],
  ['question', "What did {place} look like to you then, and what does it look like now that you know what happened there?"],
];
