// Idea bank: essay. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
// Strings use double quotes so apostrophes read naturally; the text itself never contains quotation marks.
export default [
  // ── spark ───────────────────────────────────────────────────────────────────
  ['spark', "An essay shaped like a long apology to someone who never asked for one, slowly revealing that the person who needed it most is the one offering it."],
  ['spark', "A piece about the object your family argued over politely for years, until the politeness itself becomes the real subject."],
  ['spark', "Take a skill you were praised for as a child and ask, kindly but without mercy, who the praise was really for."],
  ['spark', "Two versions of the same year, one from the family story and one from whatever is left in the drawer, with the essay living in the gap between them."],
  ['spark', "A small, unflattering admission about {topic} that you have been editing out of conversations for years, given the whole essay instead of a throwaway aside."],
  ['spark', "An essay about something you got good at by accident, and the odd grief of realising the accident was the best part."],
  ['spark', "A love letter to a bad habit, honest enough that the habit starts to look like a loyal friend and a slow thief at the same time."],
  ['spark', "Take the most boring day of your childhood and treat it as the hinge, asking what was decided that afternoon while nobody was looking."],
  ['spark', "{Theme}, approached through one repeated chore, the way you might come to understand a whole country by watching a single market stall."],
  ['spark', "A defence of something everyone treats as a minor nuisance, argued with the full seriousness usually saved for a great cause, until the reader starts to agree and resents it."],
  ['spark', "A memoir piece about the version of you who existed for one summer only, and what that stranger would make of your life now."],
  ['spark', "What {place} knew about your family before you did, and what it has quietly kept to itself ever since."],
  ['spark', "A route you have walked so many times it has become invisible, and the odd essay that appears when you force yourself to treat it as foreign ground."],
  ['spark', "The opinion you keep almost voicing at dinner tables, and the careful essay it would take to say it without losing anyone in the room."],
  ['spark', "Pick a word you have never managed to say sincerely, and let the essay find out what avoiding it has been protecting you from."],

  // ── angle ───────────────────────────────────────────────────────────────────
  ['angle', "Come at {topic} through the people who were in the room but never in the story, the ones everyone else remembers as scenery."],
  ['angle', "The late-arrival angle: you meet the subject after everything important has happened, with only leftovers, rumours and half-kept objects to reason from."],
  ['angle', "The angle of being wrong in real time, with the narrator refusing to pretend the wisdom of hindsight was available back then."],
  ['angle', "Come at {topic} by way of the single most boring question available, and follow that question until it stops being boring."],
  ['angle', "Approach a huge feeling by way of its smallest logistics: the timetables, the paperwork, the exact cost of getting somewhere you did not want to go."],
  ['angle', "Choose the angle that makes you a minor character in your own story, with someone else's decision at the centre and you watching from the edge."],
  ['angle', "Come in through a trade or a practical craft you learned alongside the thing that hurt, so grief arrives disguised as expertise."],
  ['angle', "What if the essay is not about what happened but about who has been allowed to tell it since, and who got corrected?"],
  ['angle', "A comic angle on {topic}, honest enough that the humour becomes a way of paying attention rather than a way of leaving."],
  ['angle', "{Theme} seen from the opposite seat: the person who caused it, witnessed it or benefited from it, given a fair hearing by someone with every reason not to."],
  ['angle', "The angle of the inheritor: what did you receive from the people before you that you never asked for, never use and cannot throw away?"],
  ['angle', "Look at {place} the way a visitor would, noting everything they would find odd, then ask which of those oddities you would still defend."],
  ['angle', "Frame it as the argument you keep losing to one particular friend, so every claim has to survive someone who loves you and is still not convinced."],
  ['angle', "Come in through a single word that means something different to every person who uses it, and tour those meanings until yours looks like just another guess."],

  // ── hook ────────────────────────────────────────────────────────────────────
  ['hook', "Drop the reader into the middle of an argument, at the exchange that mattered, and let them catch up on who is arguing and why."],
  ['hook', "Start with a rule your family followed without ever stating it, and let the first crack in that rule be the reason for the essay."],
  ['hook', "Open with the smallest object that survived, and make the reader wonder exactly what it survived."],
  ['hook', "Lead with a small confession, light enough to be funny and specific enough that the reader senses it is the thin end of something larger."],
  ['hook', "Enter at the moment after: the quiet where nobody knows what to do with their hands, with the cause fetched later."],
  ['hook', "Begin with something you only learned as an adult about {place}, somewhere you thought you knew completely, so the whole past tilts slightly."],
  ['hook', "Open with a misunderstanding you held for years so confidently that the reader holds it too, until the piece gently takes it away."],
  ['hook', "Use a prohibition as the hook: a room, a drawer, a road or a topic you were told never to approach, and the lure of finally going near it."],
  ['hook', "Start with the most ordinary, unremarkable weekday version of {topic}, so that any strangeness has to arrive on its own."],
  ['hook', "A question a child once asked you, one you could not answer, as the first thing the reader meets, with the essay as a very late reply."],
  ['hook', "Promise one story, a holiday or a wedding or a move, while keeping the real story in the corner of the frame until the reader leans toward it."],
  ['hook', "Open on {place} at an hour when nobody is meant to be there, so the reader arrives as a trespasser rather than a guest."],
  ['hook', "Begin with the smallest physical sign of {theme} you ever noticed in someone else, before you understood it was also in you."],
  ['hook', "Open with a claim you half believe and half suspect is ridiculous, and let the reader watch which half wins."],
  ['hook', "Open by politely declining to explain something that is obvious to you and mysterious to everyone else, and let the reader's curiosity do the pulling."],

  // ── thread ──────────────────────────────────────────────────────────────────
  ['thread', "Follow a single object that keeps changing hands, a borrowed ladder, an oversized coat or a cracked bowl, with each reappearance revealing a different relationship to whoever holds it."],
  ['thread', "Ask the same question at every stage of life and let it earn a different answer each time, the answers adding up to a portrait of how you changed."],
  ['thread', "A through-line of thresholds: every section catches you on one, going in or out or lingering, and what the doorway asks of you shifts each time."],
  ['thread', "Let {theme} be the thread but never the word, appearing only through behaviour, in the things people do when they believe nobody is counting."],
  ['thread', "Let one sense carry the whole piece, so every section is reached through what could be heard, smelled or touched, with sight rationed on purpose."],
  ['thread', "Inherited sayings that moved through your family unchecked, each one examined for who first needed it to be true."],
  ['thread', "Trace a skill that gets passed down badly, with every lesson teaching something other than what it was meant to teach."],
  ['thread', "One unanswered letter, call or message as the hanging thread, each section approaching it from closer in and flinching at a different distance."],
  ['thread', "Money as the quiet through-line: who paid, who owed, who pretended not to keep count, read as a language of love and of leverage at once."],
  ['thread', "A pattern of departures, each a different kind of leaving, until the reader sees what you were running toward all along."],
  ['thread', "A running joke that gets less funny with each return, until the essay is plainly about what the joke was covering for."],
  ['thread', "Let {place} change slowly from section to section, its repairs, closures and rearranged furniture marking time better than any date could."],
  ['thread', "Let the through-line be your changing relationship to {topic}, each section catching you at a different age and a different level of certainty."],
  ['thread', "Track a single word as its meaning shifts, each section using it differently and each use exposing what the last one hid."],

  // ── structure ───────────────────────────────────────────────────────────────
  ['structure', "A braided essay with two strands, an old story and a current question, alternating until the strands begin to answer each other."],
  ['structure', "Organise it as a walk through the rooms of one house, in an order that is emotional rather than architectural."],
  ['structure', "Let footnotes or asides slowly take over the page, until the thing they were meant to annotate becomes the aside."],
  ['structure', "Reverse chronology: start where things ended up and move backward until the reader understands why the opening felt so quiet."],
  ['structure', "One long scene held almost still, with digressions that each carry a different decade into the room and then leave again."],
  ['structure', "Build it as a glossary: each section defines one ordinary word, and the definitions grow less neutral and more personal until the last entry cannot stay an entry."],
  ['structure', "Show a before and an after and leave out the middle, letting the reader build the bridge you cannot bear to look at."],
  ['structure', "Make it a conversation with one person who is never quoted, so each section answers something the reader cannot hear and has to reconstruct."],
  ['structure', "Hang the piece on a recipe, a route or a set of instructions, where the steps are the skeleton and the life leaks out between them."],
  ['structure', "Make the shape deliberately lopsided: one long, loving stretch about something trivial, then a single very short section about the thing that mattered."],
  ['structure', "Head each section with a different name for the same event, so that what people have called it becomes the argument."],
  ['structure', "Alternate between abstract thought about {topic} and a plain description of something you can touch, so every idea has to survive contact with an object."],
  ['structure', "Let {topic} arrive only in the final section, after everything before it has quietly cleared the ground."],

  // ── turn ────────────────────────────────────────────────────────────────────
  ['turn', "The realisation that the thing you avoided for years was far smaller than the avoiding, and that the avoiding is what you actually built your life around."],
  ['turn', "Halfway through, the essay admits that its own framing was a way of staying comfortable, and the turn is the cost of that admission."],
  ['turn', "The moment the question changes: you thought you were asking why it happened and you were really asking why you needed it to have happened that way."],
  ['turn', "Build the turn from a tiny fact, a date or a receipt or a mispronounced name, that quietly overturns the story you have told for years."],
  ['turn', "Let the turn come from outside: a stranger's offhand remark, an overheard conversation or a child's literal reading that reorders what you thought about {topic}."],
  ['turn', "Turn toward generosity: let the accusation soften into understanding without absolving anyone of anything."],
  ['turn', "A turn in the opposite direction: you begin by seeking forgiveness and end by discovering you were never the one who needed to ask."],
  ['turn', "The discovery that what you were mourning was never the loss itself but the version of yourself that would have existed otherwise."],
  ['turn', "An insight about {theme} that the evidence reluctantly supports but you would rather not hold, with the essay honest about how unwelcome it is."],
  ['turn', "A turn where the narrator stops explaining and simply notices, the voice going quiet and concrete exactly where the argument would normally speak up."],
  ['turn', "A turn against your own thesis: the evidence you gathered to prove one point begins arguing for its neighbour, and the essay agrees to follow it."],
  ['turn', "The moment you notice that {who} was frightened too, and every earlier scene needs to be seen again with that fact standing in it."],
  ['turn', "The turn where you realise {place} was never just the backdrop but the cause, shaping everyone's choices from the first scene."],
  ['turn', "A turn that hardens rather than softens: after all the fair-mindedness, one plain refusal to understand or excuse something, standing at the centre of the piece."],
  ['turn', "A turn that arrives through humour: a laugh at the worst possible moment cracks the seriousness open, and what comes through is the real feeling."],

  // ── scene ───────────────────────────────────────────────────────────────────
  ['scene', "The last time you were completely certain about something that turned out to be wrong, and who was standing nearby when it stopped being true."],
  ['scene', "A meal where the food was fine and everything around it was not: who sat where, who left early, who stayed behind to wash up."],
  ['scene', "The first time you saw a grown-up unsure what to do, and how that quietly rearranged your idea of who was in charge."],
  ['scene', "A car journey with someone who could only say what they meant when both of you were facing forward."],
  ['scene', "A game, ritual or family tradition you took part in without knowing the rules, and the moment you realised everybody else did."],
  ['scene', "A moment of being good at something in front of the person whose approval you were quietly working for, and what their face did."],
  ['scene', "A time you were a stranger somewhere everyone else belonged, and what you did to look as if you knew where to stand."],
  ['scene', "A small, specific act of kindness you received and were too proud to acknowledge, from someone who may never know."],
  ['scene', "A hiding place in {place}, and everything you could hear, smell and misunderstand from inside it."],
  ['scene', "A job you hated, were too young for or loved more than made sense, and the particular people it put you beside."],
  ['scene', "A time you were being measured, interviewed, tested or judged, and what your hands were doing while you waited."],
  ['scene', "A phone call that ran longer than either of you intended, the point of it arriving only in the last stretch of silence."],
  ['scene', "The one memory of {who} that does not fit the version everyone else tells, and why you have kept it to yourself."],
  ['scene', "The first time you noticed {topic}, before you had a name for it, and who happened to be with you."],
  ['scene', "Something that happened in {place} that nobody has mentioned since, and what the silence has been holding up."],
  ['scene', "A stranger who changed your mind about something in under a minute, and the thing they did not know they had done."],

  // ── tension ─────────────────────────────────────────────────────────────────
  ['tension', "The tidy shape the story wants against the ragged, repetitive way it actually unfolded, with the essay deciding how much untidiness a reader can bear."],
  ['tension', "Let the narrator still love the thing being criticised, so every judgement visibly costs something and the reader can see the price."],
  ['tension', "The gap between what you felt then and what you are allowed to feel now, with the essay refusing to settle the argument in favour of either."],
  ['tension', "A fact you are not sure you have the right to tell because it belongs to someone else, and an essay honest about that hesitation."],
  ['tension', "The essay's argument about {theme} points one way while its examples keep drifting the other, and the honest move is to let the drift stand."],
  ['tension', "The suspicion that your best material is also your most convenient material, and that the story you tell well may be the one that lets you skip another."],
  ['tension', "A belief you hold and a habit you keep that flatly contradict each other, with the essay refusing to resolve it in favour of the more flattering one."],
  ['tension', "Two people who remember the same event in incompatible ways, and you, who loved both of them, declining to play judge."],
  ['tension', "Wanting the reader's sympathy and wanting their respect, two different appetites that pull the narrator's tone in opposite directions."],
  ['tension', "Gratitude and anger toward the same person, allowed to sit side by side on the page without either one getting the final word."],
  ['tension', "A ticking clock inside the material, a person or a house or a story about to be gone, so every section feels the weight of what has not yet been asked."],
  ['tension', "Let {who} be right about one thing you have spent the whole essay resisting, and notice how everything around it tightens."],
  ['tension', "Let your pull toward {topic} and your suspicion of that pull share the same page, each one making the other louder."],
  ['tension', "{Place} as somewhere you are fond of and ashamed of in equal measure, with the essay refusing to flatter either feeling."],

  // ── ending ──────────────────────────────────────────────────────────────────
  ['ending', "Let the last beat be a laugh, earned and a little ashamed, that lets the reader breathe without letting anybody off the hook."],
  ['ending', "Return to the opening object or room, unchanged, so the only thing that has moved is what the reader now sees in it."],
  ['ending', "Step out of the memory into whatever is happening around you now, a noise from another room or a deadline or an interruption, and leave the past exactly where it was."],
  ['ending', "Close on a question you cannot answer yet, honest rather than coy, addressed to the person it most concerns even if they will never read it."],
  ['ending', "Finish with a gesture that completes something the story kept interrupting: a delayed apology, a returned object, a meal finally eaten to the end."],
  ['ending', "Hand the last word to someone else's point of view, one detail from the other side that the narrator can only guess at."],
  ['ending', "Refuse the neat lesson: name the moral you were tempted to end on and say plainly why the material will not carry it."],
  ['ending', "Let {theme} close the piece not as a conclusion but as a present-tense condition, still going on, with no resolution promised."],
  ['ending', "End with the practical next step you actually took, small and unglamorous, instead of the emotional summit the reader expects."],
  ['ending', "Close by widening, a single glance from the private story toward everyone who has stood in a similar doorway, held lightly and never pushed."],
  ['ending', "End by conceding the strongest objection to your own argument and leaving it standing, so the reader goes away with a live question instead of a verdict."],
  ['ending', "End on {place} as it is today, full of strangers going about an ordinary day, and leave the essay's private weight with the reader."],
  ['ending', "Close by setting what caring about {topic} has cost you beside what it has given, and stop before anyone adds it up."],

  // ── title ───────────────────────────────────────────────────────────────────
  ['title', "Name the humblest object in the essay in the title, so the reader's first meeting with the piece is something they could hold."],
  ['title', "Let the title be a plain answer to the question the essay spends its whole length asking, giving away the destination and keeping the route."],
  ['title', "Borrow a phrase your family used for something it refused to name directly, so the title itself carries the avoidance."],
  ['title', "Make a small, believable promise in the title and then break it gently, so the essay feels like a detour that turned out to be the road."],
  ['title', "Build the title around a verb the essay keeps failing to complete, so the reader feels the attempt before reading a word."],
  ['title', "Give it a title that sounds like a label or a practical instruction, with the emotional weight arriving only on a second reading."],
  ['title', "Try a two-part title where the second half contradicts the tone of the first, mirroring the essay's own divided feeling."],
  ['title', "Make the title the least dramatic true thing you can say about {topic}, trusting understatement to do the work."],
  ['title', "Title the piece after the person who is absent from it, so the reader feels the shape of the missing before meeting anyone else."],
  ['title', "Use an ordinary time of day or season as the title, small and exact, and let the essay slowly turn it into an emotional location."],
  ['title', "Take the title from a mistake, a mishearing or a child's version of a word, revealed late as the truest thing in the piece."],
  ['title', "Name {place} in the title not by what it is but by what people used it for, with the essay gradually explaining why."],
  ['title', "Let the title quietly disagree with the way {theme} is usually described, leaving the essay to justify the quarrel."],
  ['title', "Pose the title as a question only a stranger would ask, so the essay has to earn the right to answer it."],

  // ── question ────────────────────────────────────────────────────────────────
  ['question', "What do you know now that you could not have known then, and how exactly did you come to know it?"],
  ['question', "Who in this story would read the finished piece most closely, and what would they be hunting for?"],
  ['question', "What is the one thing you are unwilling to say here, and does the essay quietly depend on it?"],
  ['question', "Is this essay about what happened, about what it meant, or about what you have done with it since?"],
  ['question', "What is the part you are proudest of, and is the essay actually using it or just displaying it?"],
  ['question', "Which part of this are you most hoping to be forgiven for, and by whom?"],
  ['question', "What is {theme} doing in this piece: explaining the events, excusing them, or asking to be questioned by them?"],
  ['question', "If a stranger read only the middle of the piece, what would they think it was about, and would that be fair?"],
  ['question', "Whose permission, if anyone's, do you need to tell this, and what happens to the piece if you never get it?"],
  ['question', "What is the smallest true detail you remember about this, and what does it stubbornly refuse to explain?"],
  ['question', "Why this story now, and what changed in you that made it tellable, or impossible to keep untold?"],
  ['question', "What did caring about {topic} first cost you, and was that the right thing to be afraid of?"],
  ['question', "What does {who} want from this essay that you are not prepared to give, and what do you want from them?"],
  ['question', "What did {place} look like to you then, and what does it look like now that you know what happened there?"],
  ['question', "Which friend would disagree with you most about this, and what would they say you have left out?"],
];
