// Idea bank: poem. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
// Strings use double quotes so apostrophes read naturally; the text itself never contains quotation marks.
export default [
  // ── spark ───────────────────────────────────────────────────────────────────
  ["spark", "A love poem that never describes the beloved directly, only the small things they leave behind on the counter, the stairs and the arm of the sofa."],
  ["spark", "An apology to an ordinary object, the kettle or the left shoe, for years of being relied on and never once thanked."],
  ["spark", "A field guide to a feeling with no name, classified like a bird: where it nests, what it feeds on, and how to recognise its call from a distance."],
  ["spark", "The last completely ordinary day before everything changed, arranged so that only the reader can feel what is coming and the speaker cannot."],
  ["spark", "A lullaby sung by the one who cannot sleep to the one who sleeps perfectly well, and what the song is really asking of them."],
  ["spark", "A weather forecast for a single room in a single house, with the pressure systems standing in for who is not speaking to whom."],
  ["spark", "An ode to something everyone quietly resents, the alarm clock or the waiting room chair, praised with a perfectly straight face and total sincerity."],
  ["spark", "A conversation overheard through a wall: the poem knows the rhythm, the pauses and the laughter but not one word, and has to guess the rest."],
  ["spark", "{Place} as an elderly relative who has outlived everyone able to explain its odd habits, and is now simply put up with, and loved."],
  ["spark", "{Theme} given a small job in a small town, with a name badge and a bad shift, so the abstraction has to clock in like everyone else."],
  ["spark", "A poem for {who} made entirely of the small errands they ran for other people and never once for themselves."],
  ["spark", "A poem treating with total seriousness everything {who} has ever been told was too small to matter."],

  // ── image ───────────────────────────────────────────────────────────────────
  ["image", "Something ordinary being slowly emptied, a bath, a jar of salt, a shelf of books, used as a quiet measuring stick for how long the feeling has been going on."],
  ["image", "A tide line on a wall or a harbour post, the mark of something that rose high once and has since gone back out, leaving only the stain."],
  ["image", "Busy hands doing something small and repetitive, peeling, folding, sorting, while the face stays perfectly still and the real event happens somewhere else."],
  ["image", "A child-sized object lingering in an adult's house, a stool, a coat hook, a low step, quietly outliving the childhood it was made for."],
  ["image", "A photograph seen only from the back: the handwriting, the stain, the foxed corners, with the faces never described and never needed."],
  ["image", "Something warm cooling down, tea, a bed, an engine, a hand, used to trace a goodbye without a single mention of leaving."],
  ["image", "Small sounds turned into things you can see, a dripping tap as a string of beads, a clock as a row of stitches, so that quiet becomes visible."],
  ["image", "Something carried with great care over a long distance while nobody explains what it is, so the weight does the work an explanation would."],
  ["image", "A glove, pocket or sleeve turned inside out to show what it was secretly holding all along: crumbs, a ticket, the shape worn by a hand."],
  ["image", "{Place} caught in the half minute before or after the moment that matters, so the poem's image is the empty frame rather than the event."],
  ["image", "{Theme} as a piece of weather that has moved indoors, and what it does to the furniture, the windows and the dust."],
  ["image", "Something {who} always touches on the way out of a room, a doorframe, a coat, a switch, an image that holds a whole habit of leaving."],

  // ── form ────────────────────────────────────────────────────────────────────
  ["form", "A poem in the shape of a list that starts as plain housekeeping and, item by item, turns into a confession."],
  ["form", "A pantoum, where lines return in new positions, for a memory that changes a little every time it is retold."],
  ["form", "A single long sentence that refuses to reach its full stop, because the speaker is afraid of what happens once the thought is finished."],
  ["form", "Couplets, because the subject is two people who never quite manage to share the same line."],
  ["form", "A prose poem set as one dense block, so the reader feels as hemmed in as the speaker."],
  ["form", "The form of an instruction leaflet or a recipe, with the steps growing quietly more personal until it is clear nothing here can actually be followed."],
  ["form", "A ghazal, whose refrain grows heavier each time it returns, for something the speaker keeps going back to against their better judgement."],
  ["form", "Two columns that can be read down each side or straight across, the meaning changing with how the reader crosses the gap."],
  ["form", "Line breaks placed where the speaker would catch a breath rather than where the sense ends, so the shape of the poem is the shape of a hesitation."],
  ["form", "A sonnet's tight little room for {topic}, with the poem really about everything that will not fit inside it."],
  ["form", "A form borrowed from the working life of {who}, a shift log, a checklist, a case file, so the structure itself says who they are."],
  ["form", "The shape of {place} traced on the page, with stanzas as rooms and white space as the corridors between them."],

  // ── turn ────────────────────────────────────────────────────────────────────
  ["turn", "The poem sounds calm for most of its length, and the turn is the late reveal that the calm has been an effort, held up with both hands."],
  ["turn", "A turn that comes when the poem quietly changes who it is speaking to, from a lover to a stranger, or from the living to the dead."],
  ["turn", "A single plain fact, dropped halfway through without comment, that recolours every image that came before it."],
  ["turn", "An interruption from the outside world, a knock, a ringing phone, a child's question, that the poem can neither answer nor ignore."],
  ["turn", "The speaker begins in the past tense and slides into the present at exactly the moment the distance becomes unbearable."],
  ["turn", "A sudden joke that is really the most honest moment in the poem, because grief has to breathe somewhere."],
  ["turn", "A turn that goes the wrong way on purpose: the poem seems to be heading for comfort, and the final move quietly declines it."],
  ["turn", "The turn is a missing line, a space where the poem should speak and does not, so the reader supplies what the speaker cannot."],
  ["turn", "The moment {theme} stops being the subject and becomes the listener, when the speaker realises it has been in the room all along."],
  ["turn", "A turn where {who} finally does the thing the poem has been circling, leaving the poem with no idea what to do next."],
  ["turn", "A turn that happens as the poem steps into {place} from somewhere else, so that the change of air changes everything."],

  // ── voice ───────────────────────────────────────────────────────────────────
  ["voice", "A speaker who is a house, addressing the family slowly packing up to leave it, with all the dignity a house can muster."],
  ["voice", "A gentle voice giving instructions to someone younger, who gradually turns out to be the speaker's own former self."],
  ["voice", "A speaker who has been rehearsing for years a conversation that will never happen, over-prepared and still shaking."],
  ["voice", "A collective we, a whole street or class or crowd speaking as one, with a single dissenting voice slipping through the seams."],
  ["voice", "A speaker so determined to be cheerful that the cheerfulness becomes the most worrying thing in the poem."],
  ["voice", "An expert in something very small, a watchmaker, a beekeeper, a proofreader, whose professional vocabulary leaks into how they talk about love."],
  ["voice", "A speaker who keeps correcting themselves mid-thought, taking back each claim, until the corrections reveal more than the claims did."],
  ["voice", "A voice that belongs to something left behind, a coat on a hook, an umbrella in the stand, patiently waiting to be claimed."],
  ["voice", "One plain voice held all the way through with no ornament, so the single moment of beauty feels like something the speaker could not help."],
  ["voice", "Making {who} the person addressed, a you who never answers, so the whole poem leans toward a silence."],
  ["voice", "A speaker who has spent a lifetime in {place} and now describes everything, love, weather, death, in its particular vocabulary."],
  ["voice", "{Who} narrating with total confidence and getting one crucial detail wrong, which only the reader can see."],

  // ── constraint ──────────────────────────────────────────────────────────────
  ["constraint", "A poem with no verbs at all, so everything is a noun held still and nothing is allowed to happen."],
  ["constraint", "Every line shorter than the one before it, so the poem thins out as it nears the thing it cannot say."],
  ["constraint", "One central metaphor kept up with total consistency down to the smallest detail, until it breaks, and the breaking becomes part of the poem."],
  ["constraint", "A poem that has to fit on something small, a receipt, a postcard, the back of a hand, with the surface deciding what survives."],
  ["constraint", "A draft made in the time it takes a kettle to boil, with no going back, to find out what comes out when there is no time to be clever."],
  ["constraint", "Every sentence is a question, and the poem may only answer by what it chooses to ask next."],
  ["constraint", "A single colour ruling the whole poem, so every image has to be that colour or openly admit it is not."],
  ["constraint", "Each stanza must introduce a new object and drop the last one for good, like a house being cleared room by room."],
  ["constraint", "Using only the vocabulary of one room in the house, the bathroom or the garage, to talk about something that has nothing to do with it."],
  ["constraint", "Banning {theme} as a word, along with its closest synonyms, so the idea has to arrive entirely through things."],
  ["constraint", "Everything in the poem must be something that could be found in {place}, so the large feeling has to be built from whatever is lying around."],
  ["constraint", "Only what {who} could actually see from where they are standing, with no flashback, no commentary and no looking away."],

  // ── angle ───────────────────────────────────────────────────────────────────
  ["angle", "Come at the subject from the side of whatever it replaced, the old house before the new one, the first dog before the second, and let the absence do the talking."],
  ["angle", "Look at it from the afternoon just after it all ends, when the practical chores resume and the world shows no sign of having noticed."],
  ["angle", "Look at the event from the person at its edge, the caterer, the neighbour, whoever is holding the coats, instead of from its centre."],
  ["angle", "An irritated outsider's view of the subject, all shrug and sigh, through which the poem's affection sneaks in anyway."],
  ["angle", "Treat the subject as a map, with a centre, margins, uncharted regions and someone who decided where the borders went."],
  ["angle", "Look at the subject in the language of another trade, farming, accountancy or sailing, and notice what that vocabulary exposes."],
  ["angle", "Treat the poem as the latest round of an old argument with someone no longer around to defend their side."],
  ["angle", "Gratitude arriving where grief was expected, thanking the lost thing for the exact shape of the gap it left behind."],
  ["angle", "Approach {topic} through the one small object that quietly outlasts it, letting the object carry the weight the subject is too large to hold."],
  ["angle", "Circling {topic} without once landing on it, with each image sitting a slightly different distance from the centre."],
  ["angle", "Looking at {place} at the hour nobody looks at it, and finding out what it gets up to unobserved."],
  ["angle", "{Topic} as seen by a child who has not yet learned which things are not to be mentioned."],

  // ── sound ───────────────────────────────────────────────────────────────────
  ["sound", "A single vowel sound that keeps returning like a low hum under the poem, harder to ignore the closer the speaker gets to the truth."],
  ["sound", "Soft consonants for nearly the whole poem, with the hard ones held back until the single moment anger finally gets through."],
  ["sound", "A rhythm that imitates something physical and repetitive, a kettle, a train, a rocking chair, so the poem sounds like the routine the speaker is trapped in."],
  ["sound", "Rhyme that goes missing at the exact point the speaker stops pretending everything is fine, leaving a gap you can hear."],
  ["sound", "Silence treated as a sound: very short lines, long white gaps, and punctuation that makes the reader hold their breath before the final word."],
  ["sound", "A catalogue whose rhythm speeds up as the list grows until the poem is gasping, then one long line that lets the breath out."],
  ["sound", "A refrain that changes by only one sound each time it returns, so the reader feels the meaning shift before they can say why."],
  ["sound", "A lullaby rhythm used for something that is not at all soothing, so the tune and the content pull in opposite directions."],
  ["sound", "Ending on the quietest sound available, a soft final syllable that lets the poem go out like a lamp rather than slam like a door."],
  ["sound", "Sound taken from {place}, its hums, clicks and echoes, working as the poem's secret music so the rhythm seems to come from there."],
  ["sound", "A rhythm borrowed from the way {who} walks, speaks or works, so the poem moves like them even when they are not on the page."],
  ["sound", "The sound of {theme} itself: what it would be with a pitch, a speed and a volume, and which of those the poem dares to use."],

  // ── title ───────────────────────────────────────────────────────────────────
  ["title", "A title that names the object the poem never mentions again, so the reader carries it through every line without being told to."],
  ["title", "A title that is only a time of day, leaving the poem to explain what that particular hour does to people."],
  ["title", "A title that finishes the sentence the first line begins, so the two read as one thought broken in half by white space."],
  ["title", "A title in the form of a small practical instruction, the kind found on a packet or a sign, which the poem then turns inside out."],
  ["title", "A flatly literal title, like a museum label, which the poem then contradicts within its first few lines."],
  ["title", "A title that answers a question the poem never asks aloud, so the reader has to work backwards to find it."],
  ["title", "A title that is private shorthand for a particular day, meaningless to strangers and everything to the person the poem addresses."],
  ["title", "A title that gives away the ending, followed by a poem that makes the ending hurt anyway, because knowing is not the same as being ready."],
  ["title", "A title that credits a bystander or an object as if it were the author, so the poem becomes that being's version of events."],
  ["title", "A title naming {place} only by the one thing in it that nobody notices, so the reader has to work out where they are."],
  ["title", "{Theme} left out of the title entirely and replaced by the humblest object that could stand in for it, so the title does the disguising."],
  ["title", "A title that is what {who} would call the whole affair, probably understated and probably wrong."],

  // ── question ────────────────────────────────────────────────────────────────
  ["question", "Who is the poem actually talking to, and do they know it is about them?"],
  ["question", "What is the one thing the speaker would never say out loud, and how close is the poem allowed to come to it?"],
  ["question", "Is this poem a moment or a process, a photograph of one second or a film of something slowly changing?"],
  ["question", "What does the speaker want from the reader, comfort, agreement, forgiveness or a witness, and would they ever admit it?"],
  ["question", "If the poem had a physical object at its centre, something you could hold, what would it be and who last held it?"],
  ["question", "Where does the feeling live in the body when it is strongest, and could the poem be built around that spot?"],
  ["question", "What would this poem sound like in the mouth of someone who disagrees with it completely?"],
  ["question", "How much does the reader need to know about what happened, and what would the poem gain by withholding it?"],
  ["question", "What is the smallest true thing about this subject that you have not yet allowed yourself to use?"],
  ["question", "Where does the speaker stand in relation to {topic}: inside it, beside it, or watching from far off?"],
  ["question", "Which of the reader's expectations about {theme} would you most like to disappoint, and what would you offer instead?"],
  ["question", "What is {who} not saying in the poem, and who is paying for that silence?"],
];
