// Idea bank: script. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
export default [
  // spark
  ['spark', "The character everyone keeps talking about never appears on screen, and the cast slowly realises each of them has been describing a different person, usually themselves."],
  ['spark', "Imagine a shared voicemail inbox that nobody has cleared in years, and that turns out to be the only honest record of how a family drifted apart."],
  ['spark', "Two professional negotiators fall in love across a table where each is paid to make the other lose."],
  ['spark', "What if a stage play were performed for an audience of one, who paid a small fortune for the seat and will not say why?"],
  ['spark', "A haunting seen from the ghost's side, where its biggest frustration is how badly the living tenants communicate with one another."],
  ['spark', "A sound recordist finds that the background noise captured on a film set contains a long conversation nobody remembers having."],
  ['spark', "What if {who} could pause the world for exactly one conversation a day, and spent the whole first week wasting it on the wrong person?"],
  ['spark', "{Place} has one rule that everyone follows and nobody remembers agreeing to, and the story begins the day a newcomer asks who made it."],
  ['spark', "A town's only cinema is about to close, and the vote on its final screening quietly becomes a referendum on who gets to stay."],
  ['spark', "Suppose {place} could remember every conversation held inside it, and the story begins the day it starts repeating them to the wrong people."],
  ['spark', "Picture a heist crew chosen for patience rather than skill, because the job is a three-year wait for one unlocked door."],
  ['spark', "Someone offers {who} a starring role in a documentary about their own life, on one condition: a single memory stays off camera, and the choice is theirs."],

  // premise
  ['premise', "A night-shift hospice nurse realises that three unrelated patients have each entrusted her with a piece of the same unfinished apology, addressed to a stranger."],
  ['premise', "Picture a stage play set in the forty minutes after a jury reaches its verdict but before anyone is allowed to announce it."],
  ['premise', "An audio drama assembled from the cheerful public announcements of a failing space station, where the tone slowly stops matching the facts."],
  ['premise', "A workplace comedy set in the department whose only job is to apologise on behalf of an enormous company, run by someone who has never once been sincere."],
  ['premise', "What if a road movie lost its destination in the first reel, leaving two travellers with no reason to share a car and every reason to?"],
  ['premise', "In a community that has quietly agreed to forget one terrible week, {who} is hired to run the annual festival that secretly commemorates it."],
  ['premise', "A thriller set entirely inside {place} over a single night, where every exit is unlocked and nobody can find a convincing reason to leave."],
  ['premise', "A mockumentary crew arrives to film a flattering profile of a small-town hero and gradually realises the town has been staging the heroics for decades."],
  ['premise', "An anthology series in which every episode is the same dinner party, hosted by a couple who never age while their guests visibly do."],
  ['premise', "A horror film about a presence that can be held at bay only by constant, exhausting politeness, and a family that has run out of patience."],
  ['premise', "A satirical series about {topic}, told from the point of view of the unglamorous clerk who has to file the paperwork afterwards."],
  ['premise', "Two frequent flyers only ever meet in the same airport lounge, and a slow-burn romance begins when they start booking longer layovers on purpose."],
  ['premise', "A family film in which the monster under the bed is a frightened lodger behind on the rent, and the child must work out what a fair landlord does."],
  ['premise', "One day, one errand: {who} sets out to return something borrowed long ago, and every stop along the way reopens a debt of a different kind."],

  // scene seeds
  ['scene', "A job interview where the interviewer is visibly more nervous than the candidate, because the candidate is the only person who knows why the last hire left."],
  ['scene', "At a border post, the officer plainly wants to wave a traveller through and is being watched by someone who plainly does not. The stake is who blinks first."],
  ['scene', "A years-overdue apology arrives just as the person owed it is handling an emergency, so the apologiser must choose between helping first and being forgiven first."],
  ['scene', "On a bar's final night, the owner wants a quiet closing, a regular wants a toast, and a stranger with a folder wants a signature before midnight."],
  ['scene', "{Who} gets a few minutes alone with the one person who could end the whole problem, and must choose between begging for help and finally saying what the trouble has cost."],
  ['scene', "In {place}, long after closing, two people who have dodged each other for months are the only ones left, and one is carrying news that will end the other's career."],
  ['scene', "A wedding speech starts as affection and drifts, sentence by sentence, towards a truth the two families agreed years ago to bury; the stake is whether anyone will cut the microphone."],
  ['scene', "Two families share a hospital waiting room after a collision that involved them both, each polite, each privately assigning blame. The stake is who finally says who was driving."],
  ['scene', "A phone call in which a stranger must be kept talking until help arrives, and the only subject the stranger will discuss is a grudge about a borrowed ladder."],
  ['scene', "Two neighbours negotiate over a single parking space with a ferocity that is plainly about something else, and one of them is only days from moving away."],
  ['scene', "The reading of a will stalls when it names a beneficiary nobody has heard of, and the one person who has is suddenly very quiet."],
  ['scene', "A dinner where the talk turns to {topic}, and one guest has a stake in it that nobody else at the table knows about."],
  ['scene', "{Who} has to deliver bad news to someone in the middle of a proud moment, and must choose between kindness now and honesty later."],

  // conflict
  ['conflict', "Two people want the same outcome for opposite reasons, so every win for one of them quietly ruins the other's real plan."],
  ['conflict', "An institution's written rules and its unwritten ones are at open war, and the hero is the only person who has memorised both sets."],
  ['conflict', "Two characters are each other's only witness to the past, so neither can afford to let the other be discredited and neither can bear being corrected."],
  ['conflict', "{Who} owes everything to a mentor whose methods have started to harm the very people the work was meant to protect."],
  ['conflict', "Two characters are in open conflict over what {theme} demands of them, each convinced the other has misunderstood it."],
  ['conflict', "Both sides have privately agreed to give way, but neither can say so without losing face in front of their own people, so the negotiation becomes a dance of staged refusals."],
  ['conflict', "The antagonist is a reasonable person doing a job well, and the audience keeps wavering because the hero's cause is the slightly unreasonable one."],
  ['conflict', "Three business partners disagree about only one thing, whether to tell a customer the truth, and the argument slowly exposes how differently each defines loyalty."],
  ['conflict', "The hero's rival is the living picture of the habit the hero most wants to break, which turns every confrontation into a self-examination."],
  ['conflict', "What if the antagonist is a faceless bureaucracy, and the drama comes from giving every clerk in the chain a small private reason to obstruct or to help?"],
  ['conflict', "A family firm splits over one question, sell or struggle on, and each branch holds a reason for its answer that it has never told the others."],
  ['conflict', "Two friends are pulled to opposite sides of a dispute that began as a joke between them, and neither can say when it stopped being one."],
  ['conflict', "{Who} wants peace, but the only way to keep it is to let someone else take the blame, and that someone is a friend."],
  ['conflict', "Two factions in {place} are divided by a rule that neither can remember the reason for, and each is sure the other benefits from it."],

  // visual
  ['visual', "One colour belongs to a single character's lies, and it begins turning up in other people's clothes and furniture as the deception spreads."],
  ['visual', "A house built as a cutaway, every room visible at once, while the characters insist they cannot hear one another through the walls."],
  ['visual', "The same doorway, framed from the same angle, opens each sequence, until the day the camera finally stands on the other side of it."],
  ['visual', "Weather stays stubbornly neutral for the entire film, so the one scene where it finally matches a character's mood lands like a thunderclap."],
  ['visual', "What if a stage set lost one object every act, so the audience realises only late that the room has been quietly packed away around them?"],
  ['visual', "A borrowed coat passes between several wearers over the course of the story, and its pockets keep revealing the life of the previous owner."],
  ['visual', "{Place} is lit warmly at the start and gradually drained of colour, so the audience feels the loss long before anyone mentions it."],
  ['visual', "A split screen reserved for phone calls, where the two halves slowly begin to share a background, a shadow, a patch of light, until the divide disappears."],
  ['visual', "An enormous disaster is shown only through one person watching from far away on a small screen, so the audience builds the catastrophe themselves."],
  ['visual', "A character is always seen in reflections, windows and screens, never directly, and the first straight-on shot arrives the moment they decide to act."],
  ['visual', "A bare stage lit by a single lamp on a long visible cord, so whoever moves the lamp moves the light, and with it the version of the truth."],
  ['visual', "Hands carry the real conversation: the camera stays on what characters do with their hands while they talk about something else entirely."],
  ['visual', "{Who} is always filmed from slightly too far away, until the single moment the camera is allowed close enough to see their face change."],
  ['visual', "Suppose a recurring shot of {place} at dawn repeats all through the story with one small detail altered each time, and the audience is never told to look for it."],

  // twist
  ['twist', "The threat everyone is bracing against ended an hour ago, and the real drama begins when they discover they are free and have no idea what to do with it."],
  ['twist', "The guide who has been explaining the rules of the world is revealed to have been wrong about all of them, in conveniently self-serving ways."],
  ['twist', "The funeral in the opening scene turns out to be for someone very much alive, and the real question becomes why everyone present needed them gone."],
  ['twist', "The assumed rival has been the only one trying to save the hero all along, and has been blocked at every turn by the hero's own good intentions."],
  ['twist', "What if the big reveal lands at the midpoint, and the rest of the story is about what people do when the secret is out but nothing has been fixed?"],
  ['twist', "An object treated as priceless all through the story is shown to be worthless, and the characters who find out must decide whether to say so."],
  ['twist', "Two timelines the audience has read as different eras turn out to be the same night, told by two people sitting at opposite ends of one table."],
  ['twist', "{Who} discovers that the person they have been protecting has been protecting them, and for much longer."],
  ['twist', "Just when {theme} seems to have won, a character everyone wrote off is revealed to have been quietly arguing the opposite case from the start."],
  ['twist', "A ringing phone in the background of several scenes is revealed to be one patient caller who has been trying to reach the hero since the first act."],
  ['twist', "In an ensemble comedy, the character treated as dead weight is shown in a late episode to be the single reason the group has held together."],
  ['twist', "The audience fears a stranger for two acts, then learns the stranger is just as frightened of the family, and for better reasons."],
  ['twist', "The thing {who} has spent the whole story hiding is already common knowledge, and everyone has been kindly pretending not to know."],
  ['twist', "The layout of {place} turns out to be the antagonist's design, and every obstacle the hero faced was built in on purpose."],

  // structure
  ['structure', "The story runs backwards scene by scene, so each new scene removes an excuse instead of adding a cause."],
  ['structure', "The whole story plays out in real time, so the act breaks come from interruptions, a phone, a knock, a delivery, rather than from jumps in the calendar."],
  ['structure', "A play in three acts, each the same evening seen by a different person, with the final act revealing the moment all three have been avoiding."],
  ['structure', "What if every episode were built around a different object in the same house, so the season becomes the story of what each object has quietly witnessed?"],
  ['structure', "The final image appears in the first minute, and each act changes what the audience thinks that image means."],
  ['structure', "A midpoint that swaps the roles: the pursuer becomes the pursued, the teacher becomes the pupil, and the second half is a mirror of the first."],
  ['structure', "Two stories intercut without ever meeting in the plot, so the rhyme between them, not any cause, carries the audience through each act."],
  ['structure', "The structure follows {who}'s attention instead of the calendar, cutting away whenever their mind drifts, so the gaps in the plot become a portrait of what they avoid."],
  ['structure', "A one-room play whose acts are divided by who is permitted to leave: each act one more person goes, and the remaining company grows more honest."],
  ['structure', "An audio drama built as a run of voice messages answered out of order, so the listener reassembles the conversation and notices what was never replied to."],
  ['structure', "A procedural in which the weekly case is solved in the first ten minutes, and the rest of each episode is about the cost of being right."],
  ['structure', "A structure that treats {topic} as a trial: each act is a different witness, and the audience is a jury never told its verdict."],

  // dynamic
  ['dynamic', "Two characters talk only about logistics, rooms and trains and deadlines, while the real negotiation about forgiveness is carried by who offers to carry what."],
  ['dynamic', "A boss desperately needs a junior employee's good opinion while the employee has quietly stopped caring, and every exchange tilts on that mismatch."],
  ['dynamic', "A pair who have finished each other's sentences for years suddenly cannot, and the scene is the first time either has to ask what the other actually means."],
  ['dynamic', "Two people must pretend to be strangers in public, and the private scene afterwards reveals they are better at it than either would like."],
  ['dynamic', "A mentor has been quietly overtaken by a former student, and both keep performing the old roles because neither can bear what the new ones would mean."],
  ['dynamic', "At a long table, the person with the least apparent power controls every decision, because everyone is watching to see whether they will object."],
  ['dynamic', "{Who} is the only person in the scene who is not lying, and the dynamic is that nobody can afford to believe them."],
  ['dynamic', "Someone who owes {who} a large favour keeps trying to repay it in the wrong currency, and each failed attempt makes the debt heavier for both."],
  ['dynamic', "Two characters are comfortable only when a third person is present, so every scene with just the two of them carries the nervous energy of a first date."],
  ['dynamic', "What if the real question under every scene between a caregiver and the person being cared for is who is allowed to have a bad day?"],
  ['dynamic', "A comic double act in which the supposedly serious one is secretly funnier and has been suppressing it for the sake of the partnership."],
  ['dynamic', "{Who} and an old rival are stuck sharing a taxi, and the whole struggle for the upper hand is fought out in small politeness."],
  ['dynamic', "A conversation between {who} and a younger relative in which each treats the other as the responsible adult."],

  // title directions (approaches, never an actual title)
  ['title', "A title taken from an everyday object that appears in the first scene and returns, unbearably changed, in the last."],
  ['title', "A title that sounds like a polite instruction on a sign or a form, so the story feels like someone obeying it and then breaking it."],
  ['title', "What if the title is a job or role that nobody in the story ever quite manages to fill?"],
  ['title', "A title named for the place that is never visited on screen, so the audience carries it as a promise the whole way."],
  ['title', "A title that is a promise one character makes early, which the rest of the story spends its time testing."],
  ['title', "A title that is accurate in the first half and ironic after the midpoint, with the same words meaning the opposite."],
  ['title', "A title that circles {theme} without ever naming it, borrowing the vocabulary of a trade, a sport or a weather forecast instead."],
  ['title', "A title built on a nickname that {who} hates, so every use of it lands as a small humiliation."],
  ['title', "A deliberately small title for an enormous story, borrowed from something as modest as a street, a timetable or a day of the week."],
  ['title', "For a series, a title that doubles as the name of the group the characters keep trying to join or leave, so every episode argues about what belonging costs."],
  ['title', "A title in the grammar of a lost-property label or a missing-person notice, so the audience reads the story as a search before it begins."],
  ['title', "A title that names the one room in {place} where the real story takes place, though the audience barely sees it until the end."],

  // question
  ['question', "What does the audience know in the first scene that the characters do not, and who benefits from keeping it that way?"],
  ['question', "What is the one scene you can already see clearly, and what has to be true before it for it to land as hard as it does in your head?"],
  ['question', "Where does this live: a stage, a screen or a pair of headphones? And what can that format do that the other two could not?"],
  ['question', "If this were a series, what unanswered question would make a viewer press play on the second episode?"],
  ['question', "What does {who} want in the first scene, what would they say they want if asked, and are the two answers different?"],
  ['question', "Why is this story happening in {place} and not somewhere else, and what would break if it moved?"],
  ['question', "Whose silence is the loudest thing in the script, and what would it cost them to finally speak?"],
  ['question', "How much of the story could be followed with the sound off, and how much with the picture off? Which one is the real script?"],
  ['question', "Which character most disagrees with {theme}, and have they been given a fair case to make rather than a straw man?"],
  ['question', "What is the smallest event that could start this story, and what is the largest thing it could cost?"],
  ['question', "What does the main character's ordinary day look like before anything goes wrong, and what is the first thing in it that will be lost?"],
  ['question', "What would a sceptical viewer say is wrong with a script about {topic}, and does the script already know the answer?"],
  ['question', "Who in the story knows what {theme} costs, and who is the last to find out?"],
];
