// Idea bank: story. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
// Strings use double quotes so apostrophes read naturally; the text itself never contains quotation marks.
export default [
  // ── spark ───────────────────────────────────────────────────────────────────
  ['spark', "A lighthouse that guides ships away from the coast instead of toward it, and a keeper who has never been told why."],
  ['spark', "Two strangers keep receiving each other's post, and the misdelivered letters slowly start answering questions the other never asked aloud."],
  ['spark', "A village where every family must surrender one memory a year to a communal archive, and {who} is the first to ask what is done with them."],
  ['spark', "The last speaker of a fading language is also the only witness to a crime, and the only way to take their testimony is to teach someone the language first."],
  ['spark', "A heist crew discovers that the vault they are robbing was built, long ago, to be robbed by exactly this crew."],
  ['spark', "A haunted house whose ghost is desperate for the living family to stay, so the haunting is really a campaign of hospitality gone wrong."],
  ['spark', "An ordinary kitchen chair is insured for a fortune, and the only person who knows why is the one who keeps sitting in it."],
  ['spark', "On a generation ship whose oldest rule is never to open the sealed corridor, {who} is handed the only key by a stranger who then forgets doing so."],
  ['spark', "A wedding where every guest has separately come with the intention of stopping it, and none of them knows about the others."],
  ['spark', "{Place} has a back room nobody remembers building, and the only person who can find the way in is someone who has never been there."],
  ['spark', "A town holds a yearly festival devoted to {theme}, which everyone attends and nobody can explain, until an outsider asks the one question that matters."],
  ['spark', "A cartographer hired to map a country that rearranges itself overnight slowly realises that the changes track her own moods."],
  ['spark', "A mystery whose culprit is found on the first day, leaving the rest of the story to work out why everyone is so relieved."],
  ['spark', "After a funeral, three siblings find that their late mother kept a meticulous ledger of every favour she ever did them and what she hoped to be repaid."],

  // ── premise ─────────────────────────────────────────────────────────────────
  ['premise', "A retired locksmith learns that every lock she ever fitted in the old town was quietly opened, years ago, by one person, and sets out to find what they were looking for."],
  ['premise', "In a city where grief is taxed and mourners pay for every day they stay sad, a funeral clerk begins quietly losing the invoices of mourners who cannot pay."],
  ['premise', "A ghost who does not know she is dead hires a living private investigator to find out who has been moving into her house and rearranging her life."],
  ['premise', "Two rival bakers in a snowbound village discover they are the only ones with flour left, and the village survives only if they cooperate in a way their families never have."],
  ['premise', "A conference interpreter has been quietly softening both delegations' words for days, and realises the peace everyone is celebrating rests entirely on her small lies."],
  ['premise', "A boy inherits a failing roadside motel from an uncle he never met and learns that every guest who ever stayed there is still, technically, checked in."],
  ['premise', "A small-time smuggler discovers that the cargo she has carried for years is slowly assembling itself into something, one crate at a time."],
  ['premise', "A government auditor sent to shut down the last paper archive in the country finds herself defending it, one misfiled folder at a time."],
  ['premise', "Twin sisters swapped places as a childhood prank and never managed to swap back; now one is accused of a crime, and the only alibi belongs to the wrong sister."],
  ['premise', "A dragon applies to join the local fire brigade, and the town must decide whether being the thing everyone fears makes it the best or the worst candidate."],
  ['premise', "Two ex-spouses are each secretly hired by the same matchmaker to find the other a new partner, and turn out to be far too good at the job."],
  ['premise', "{Who} wakes to find that everyone they know has agreed, overnight and for no stated reason, to treat them as a stranger."],
  ['premise', "{Who} has one more day to hide a terrible mistake, and the only person able to help is the one it will hurt most."],
  ['premise', "The last two people still in {place} after everyone else has gone each believe the other is the reason nobody can leave."],

  // ── next ────────────────────────────────────────────────────────────────────
  ['next', "The one person who has stayed silent in every scene so far finally speaks, and the group realises they have known the answer all along."],
  ['next', "{Who} gets exactly what they wanted, a little too early, and has to decide whether to keep going now that the goal has stopped being the point."],
  ['next', "An ally is forced to choose a side and picks the one nobody expected, out of a loyalty the reader has not been told about yet."],
  ['next', "The plan works perfectly, and the consequences of it working become the engine of the next stretch of the story."],
  ['next', "Skip the big confrontation entirely and let the next scene reveal its outcome through one small side effect, such as a missing coat or a changed seat at the table."],
  ['next', "{Who} is offered help by the last person they would ever accept it from, and has to weigh how much pride is worth right now."],
  ['next', "A rule the story established so lightly that the reader may have forgotten it is suddenly tested in earnest."],
  ['next', "Someone leaves, not dramatically and not forever, just far enough that everything must be rearranged around the empty chair."],
  ['next', "The pursuer gives up, and the one being chased has to decide what to do with a freedom they spent the whole story running toward."],
  ['next', "Two threads that have run in parallel collide somewhere ordinary, a laundrette or a bus stop, and neither person yet understands what they are standing next to."],
  ['next', "A message arrives that was meant for someone else, and the wrong person acts on it."],
  ['next', "{Who} finds that the person they have been avoiding has been quietly doing them favours, and has to work out what the debt is worth."],
  ['next', "A small thing goes wrong in {place} that has nothing to do with the plot, and the characters lose precious time searching for the connection."],

  // ── twist ───────────────────────────────────────────────────────────────────
  ['twist', "The one person {who} trusts to keep a secret is the person it is being kept from."],
  ['twist', "Every lesson the mentor ever gave was designed to keep the student away from one particular door, and the student is about to walk through it anyway."],
  ['twist', "The ghost has been in the house all along, and it turns out the living family is the haunting."],
  ['twist', "The missing person was never taken; they left, with help, and the helper is someone the search party has been thanking all along."],
  ['twist', "The letters that drive the story were all written by one person pretending to be several, and the reason is lonelier than any plot."],
  ['twist', "Put the biggest revelation a third of the way in, and make the remaining story about how everyone behaves once they know."],
  ['twist', "The captive was never being held. They could have left at any point and keep choosing to stay, and the reason is what the story is really about."],
  ['twist', "The treasure everyone is hunting was found and spent generations ago, and the legend survives only because one family needs it to."],
  ['twist', "The shadowy conspiracy hiding in plain sight turns out to be a badly run committee, and every sinister result was a clerical error."],
  ['twist', "{Who} is the answer to the question the whole cast has been asking, and the last to find out."],
  ['twist', "The apparent accident was the second thing to happen that night, and the first is the thing someone has worked hard to make unremarkable."],
  ['twist', "Everything {who} learned in the first act was true, but it was delivered in exactly the order that guaranteed the wrong conclusion."],
  ['twist', "{Who}'s most reliable memory turns out to belong to someone else, and the whole story has been running on a borrowed past."],

  // ── opposite ────────────────────────────────────────────────────────────────
  ['opposite', "Flip the prophecy: instead of a hero destined to win, an entire society has arranged itself to make sure the hero fails on schedule."],
  ['opposite', "Turn the race around so nobody is trying to reach the finish and everyone is desperate to be the last to arrive."],
  ['opposite', "Flip the rescue: the person in the tower has a perfectly good plan, and the knight arriving at the door is the complication they have to manage."],
  ['opposite', "Let {who} be the one everyone else is trying to protect from the truth, rather than the one chasing it."],
  ['opposite', "Reverse the register: treat the catastrophe as a gentle comedy of manners, or a wedding as a thriller, and let the mood argue with the events."],
  ['opposite', "Flip who is afraid: the monster is terrified of the village, and every frightening thing it does is a clumsy attempt to get away."],
  ['opposite', "Flip the information: instead of the hero being kept in the dark, the hero knows everything from the start and the suspense is whether anyone will believe them."],
  ['opposite', "Flip the desire: everyone is trying to get rid of the thing the genre says they should want, a crown, a fortune or a title, and it keeps coming back."],
  ['opposite', "Let the villain win in the first act, and make the story about living in the world afterwards, with the hero reduced to trying to be ordinary."],
  ['opposite', "Take {place} and flip its reputation: if it is known as welcoming, make it impossible to escape; if it is feared, make it the last kind place left."],
  ['opposite', "Swap the ages: the child is the tired, wary cynic, and the grandparent is the one who still believes the impossible can happen."],
  ['opposite', "Turn {who}'s greatest strength upside down and make it the reason the central problem exists in the first place."],

  // ── stakes ──────────────────────────────────────────────────────────────────
  ['stakes', "Make the thing at risk something {who} has already promised to someone else, so failing means breaking two promises at once."],
  ['stakes', "Give the failure a witness: if the plan falls apart, the one person whose opinion matters most will be standing right there watching."],
  ['stakes', "Attach a quiet deadline to the loud one: the verdict is due, but so is a birthday, a visa renewal or a harvest that has nothing to do with it."],
  ['stakes', "Let winning cost something that cannot be bought back: a friendship, a good name, a home town, or the ability to go back to being ordinary."],
  ['stakes', "Make the stakes collective: if the protagonist fails, nobody is hurt at once, but the small unspoken agreement holding a whole community together quietly dissolves."],
  ['stakes', "Put the thing at risk into someone else's hands halfway through, so the hero must watch a person they do not fully trust carry what matters most."],
  ['stakes', "Raise the price of the quiet option: let staying out of it become more dangerous than getting involved, so retreat stops being safe."],
  ['stakes', "Tie the outcome to an old mistake: if {who} fails now, it proves the worst thing anyone ever said about them was true."],
  ['stakes', "Give the villain something to lose too, so the final confrontation is between two people each defending something they love."],
  ['stakes', "Let every success take something small and irreplaceable from {who}, so the story becomes a question of how many wins are survivable."],
  ['stakes', "Raise the stakes sideways: instead of a bigger disaster, endanger the one small thing that explains who the character is, a workshop, a garden, a private name for themselves."],
  ['stakes', "Let the price of failure be that {place} stops being a refuge, so even people who never took part lose somewhere they relied on."],
  ['stakes', "Make failure invisible: if {who} fails, the person they were trying to protect never finds out, and the cost is carried alone."],

  // ── complication ────────────────────────────────────────────────────────────
  ['complication', "The helper who turns up at the perfect moment has a deadline of their own, which makes their help conditional and slightly urgent."],
  ['complication', "The key tool, map or piece of evidence can only be used once, and two people need it at the same time."],
  ['complication', "The plan depends on someone {who} has wronged, who happens to be the only person holding what is needed."],
  ['complication', "The easy route closes behind them, through a storm, a strike or a sudden change of rules, and the only way left costs something personal."],
  ['complication', "Give {who} a perfectly good reason to do the wrong thing: loyalty, kindness or plain exhaustion makes the obstacle feel like a duty."],
  ['complication', "What they need is available, but only in exchange for telling the truth about something they have never admitted aloud."],
  ['complication', "An innocent attaches themselves to the mission, a child, a stowaway or a well-meaning neighbour, and now every risk has a second set of consequences."],
  ['complication', "The authority they were counting on is away, newly replaced or quietly compromised, and the new person has not heard the story and does not much care."],
  ['complication', "A success in one scene creates a small debt of gratitude, and the person owed will call it in at the worst possible moment."],
  ['complication', "Take away the one skill {who} is proudest of for a stretch of the story, and force them to solve the problem as a beginner."],
  ['complication', "Two goals that looked compatible start grinding against each other: helping one friend means harming another, and neither will agree to wait."],
  ['complication', "{Place} pushes back: every simple task takes longer there, through closed doors, strange customs and people who refuse to be hurried."],
  ['complication', "{Who} is asked to keep a promise made by someone who is no longer around to explain what they meant by it."],

  // ── secret ──────────────────────────────────────────────────────────────────
  ['secret', "A character everyone treats as ordinary is quietly keeping the community's most important record, and has been tempted for years to burn it."],
  ['secret', "{Who} knows exactly who did it and has chosen not to say, for a reason that has nothing to do with protecting the guilty party."],
  ['secret', "The family fortune, house or good name rests on a single dishonest act that only the eldest member remembers, and that memory is beginning to fail."],
  ['secret', "Two characters are guarding the same secret from each other, each certain they are the only one who knows."],
  ['secret', "The secret is not a shameful act but a kindness: someone has been quietly paying a debt or protecting someone, and revealing it would humiliate the person helped."],
  ['secret', "Everyone in the story already knows the hidden thing and is performing ignorance out of politeness. The only one who truly does not know is the person it is about."],
  ['secret', "A character is hiding not a crime but an ability, a talent or a feeling, and fears its being noticed far more than any punishment."],
  ['secret', "The secret is stored in a mundane object, a coat, a casserole dish or a borrowed book, that passes from hand to hand while its true weight goes unnoticed."],
  ['secret', "Someone lies about where they were at a key moment, not to cover a crime but because they were somewhere they would rather be found guilty than admit to."],
  ['secret', "A person with the power to end the conflict stays quiet because the conflict is the only thing keeping a divided family in the same room."],
  ['secret', "What {who} calls a secret is actually a lie they have been telling themselves, and someone else in the story has noticed."],
  ['secret', "Something is buried, bricked up or boarded over in {place}, and the one who knows where keeps volunteering to supervise any building work."],
  ['secret', "{Who} has been taking credit for something they did not do, and the real author is in the room, silent, for a price nobody has named."],

  // ── conflict ────────────────────────────────────────────────────────────────
  ['conflict', "Two people want the same thing for opposite and equally good reasons, and a third person is quietly benefiting from their stalemate."],
  ['conflict', "The antagonist is an institution with no single villain: a committee, a policy or a tradition, in which every individual is polite and sympathetic."],
  ['conflict', "Pit loyalty to a person against loyalty to a principle, and make {who} choose in a room where both are watching."],
  ['conflict', "Two people who lived through the same event hold incompatible memories of it, and each needs the other's version to be wrong in order to go on living with their own."],
  ['conflict', "A friendship is tested not by a betrayal but by one friend's success, which the other cannot help resenting."],
  ['conflict', "The fight is between {who} and the version of themselves from earlier in the story, whose promises are now being held against them."],
  ['conflict', "Two rival experts are forced to share a case, a kitchen or a lifeboat, and each privately believes the other's method is going to get someone hurt."],
  ['conflict', "The antagonist is something nobody can argue with, a flood, a failing harvest or a slow illness, so the real conflict is among those who disagree about how to face it."],
  ['conflict', "A newcomer's perfectly reasonable request threatens a tradition the community has never had to justify, and for the first time someone must explain why things are done this way."],
  ['conflict', "Make the antagonist right about one thing the hero is wrong about, so that every scene between them is a genuine argument rather than a threat."],
  ['conflict', "Two groups both believe {place} belongs to them, and each has a perfectly reasonable story about why."],
  ['conflict', "{Who} falls out with their oldest friend over something small, and it becomes clear that the small thing was never what the argument was about."],
  ['conflict', "Let two characters disagree about {theme} in earnest, and make the argument itself drive events instead of pausing them."],
  ['conflict', "Let the conflict be a quarrel over how to grieve, with one person who wants to keep everything exactly as it was and one who wants to clear it all out."],

  // ── theme ───────────────────────────────────────────────────────────────────
  ['theme', "Treat the story as an argument about whether forgiveness is something you give or something you can afford."],
  ['theme', "Let {theme} be tested rather than illustrated: give the story a character who sincerely and intelligently disagrees about it, and let them hold their ground."],
  ['theme', "Consider whether the story is really about inheritance, not of money but of habits, fears and ways of staying quiet, and who gets to refuse it."],
  ['theme', "What if the story is about the gap between being needed and being loved, with every relationship sitting at a different point along that gap?"],
  ['theme', "Look for the theme in what the characters are tired of rather than what they are fighting for, because exhaustion often shows what a story truly cares about."],
  ['theme', "Let {theme} show up in the story's smallest transactions, a favour, a borrowed tool, a shared meal, so the big events only confirm what the small ones already said."],
  ['theme', "A story about the cost of being the one who stays: the person who keeps the house, the town or the family running while everyone else gets to leave."],
  ['theme', "Make the story argue with a proverb, not by mocking it but by building a world where it is perfectly true and showing who it ruins."],
  ['theme', "The theme could be honesty against kindness, with each major character having made a different, defensible trade between the two."],
  ['theme', "Build the story around what it means to be believed: who gets believed, who does not, and what each of them pays for it."],
  ['theme', "What if the story is secretly about repair, the slow, unglamorous work of mending something after the dramatic damage is over?"],
  ['theme', "What if {theme} is not the problem the story solves but the condition everyone lives under, and the real question is how to carry it well?"],
  ['theme', "Ask what {theme} would look like in a character who is very good at hiding it, and let the reader notice before anyone else does."],
  ['theme', "Imagine {who} as a living argument about {theme}, and then give them an opponent who is a better argument."],

  // ── ending ──────────────────────────────────────────────────────────────────
  ['ending', "End with the goal achieved and the hero standing in the quiet that follows, unsure what they are for now."],
  ['ending', "Let the final image echo the first one with a single changed detail, so the reader feels the whole distance travelled without a word of explanation."],
  ['ending', "End one beat before the decision, with the character at the door and the reader fully aware of both options, so the choice belongs to the reader."],
  ['ending', "Give the villain the last scene, quiet and unobserved, so the victory feels like a pause rather than a conclusion."],
  ['ending', "Let the ending be a repair: nothing big resolves, but one small broken thing, a friendship, a fence, a family recipe, is finally mended."],
  ['ending', "Reveal the secret only to the reader, in the final moments, so the characters go on living inside a version of events we now know is wrong."],
  ['ending', "Let the happy ending be earned and uncomplicated, and trust the reader to enjoy it without a sting in the tail."],
  ['ending', "Close on the aftermath of a minor character, someone who was changed by the events without ever understanding what happened."],
  ['ending', "Hinge the ending on a small act of mercy the character could easily have skipped, and let the reader see what it cost."],
  ['ending', "End with a handover: the object, the role or the story itself passes to someone new, and the cycle begins again with one slight difference."],
  ['ending', "End by letting {place} carry on as though nothing has happened, so the reader alone carries what the characters left behind."],
  ['ending', "Let {who} finally say the thing they have avoided saying, and make the ending what happens in the silence afterwards."],
  ['ending', "Close with {theme} winning one small, undeniable victory in a single gesture while the larger problem stays exactly as it was."],
  ['ending', "End with {who} choosing the smaller life they once feared, and leave the reader unsure whether to cheer."],

  // ── opening ─────────────────────────────────────────────────────────────────
  ['opening', "Begin the day after the event most stories would save for the middle, when the consequences are still being cleaned up and nobody knows what to say."],
  ['opening', "Open in the middle of an ordinary routine carried out with great care, a morning ritual or a daily chore, so that when it breaks the reader feels it."],
  ['opening', "Start with a character leaving a place for the last time, and keep the reason hidden until the end of the story."],
  ['opening', "Begin with a rule being explained to a newcomer, so the reader learns how things work and learns that someone is about to break it."],
  ['opening', "Open on an object that has just been found and an argument about whether to tell anyone."],
  ['opening', "Begin from a vantage nobody would choose, the ceiling, the lost-property office, the back of the room, so that the central event is only half seen."],
  ['opening', "Open just before something small and irreversible: a signature, a handshake, a lie told as a favour."],
  ['opening', "Put the reader in the middle of a rumour, with the first pages devoted to what people are saying before the person at the centre has appeared."],
  ['opening', "Begin with the tail end of someone else's story, the one that has just finished, and let {who}'s arrive as its side effect."],
  ['opening', "Open at a ceremony where one small thing is already wrong and everyone is carefully ignoring it."],
  ['opening', "Start in a place of safety on the last day it will be safe, so every comfortable detail carries a hidden countdown."],
  ['opening', "Begin with someone arriving in {place} who is clearly not supposed to be there, and let nobody challenge them for a suspiciously long time."],
  ['opening', "Open on {who} in the middle of a small act of competence, so the reader trusts them before there is any reason to."],

  // ── pov ─────────────────────────────────────────────────────────────────────
  ['pov', "Tell it through someone who is not the hero but is closest to the hero, and who misreads the hero's motives with complete confidence."],
  ['pov', "Let the narrator be the place itself, a house, a village or a ship, which has watched generations pass and cares more about some of them than it should."],
  ['pov', "Use a collective voice, a family, a crew or a whole town speaking as we, and let the cracks show when one member disagrees and the voice cannot quite hold."],
  ['pov', "Give the narration to the person who gets the story wrong in the most understandable way: loving, loyal and entirely mistaken."],
  ['pov', "Alternate between two people who lived through the same events and are each certain they were the one who got left behind."],
  ['pov', "Tell it from after the fact through a narrator who is deliberately saving the worst part for last, so the reader can feel them stalling."],
  ['pov', "Choose a viewpoint character who does not understand what they are seeing, a small child or a newcomer, and let the reader do the understanding."],
  ['pov', "What if the story is narrated by the person investigating {who}, and the more they learn, the more the narrator begins to sound like their subject?"],
  ['pov', "Stay close to someone who is pretending to be calm, so the surface of the telling is composed and the reader sees the effort underneath."],
  ['pov', "Let the viewpoint travel, passing from one person to the next like a baton at the moment each of them makes a choice."],
  ['pov', "Try a narrator who knows the ending and keeps interrupting themself, a historian, a ghost or a hopeful relative, to say how it could have gone differently."],
  ['pov', "Narrate from the point of view of the newest person in {place}, who notices everything the old hands have stopped seeing."],
  ['pov', "Tell it through the person {who} confides in least, so every scene stays slightly out of reach and the reader fills in the rest."],

  // ── structure ───────────────────────────────────────────────────────────────
  ['structure', "Tell the story in reverse, each section revealing the cause of the one before, so the reader's question slowly shifts from what happened to why."],
  ['structure', "Build the story around one room visited at different stages of a life, with the gaps between visits carrying most of the plot."],
  ['structure', "Interleave a present thread with a past thread and let each answer a question the other has raised, though never the one it asked."],
  ['structure', "Structure it as conflicting accounts of a single event, with the truth sitting not in any one of them but in what they all avoid."],
  ['structure', "Give the story a ticking frame: it takes place across a single night, a single journey or a single meal, and everything else arrives as interruption."],
  ['structure', "Place the hinge at the exact middle, so that everything in the first half is revealed to have meant something different and the second half recasts it."],
  ['structure', "Arrange it as a series of small tests, each one passed or failed, so the reader watches a character's pattern emerge before they do."],
  ['structure', "Let the story spiral: return to the same event three times from three different distances, with each return adding one detail that changes how it felt."],
  ['structure', "Run two timelines toward each other so they meet in the last scene, with the reader knowing the meeting point long before the characters do."],
  ['structure', "Borrow the shape of a recipe, a legal case or a field guide, and let the plain format grow more strained as the events become more personal."],
  ['structure', "Hold the central event back until the very end and tell everything around it, so that its absence becomes the shape of the story."],
  ['structure', "Organise the story around the people {who} says goodbye to, one section for each, so the shape of a whole life emerges from its departures."],
  ['structure', "Let each part of the story be a different room or corner of {place}, moving inward until the last section happens where nobody is meant to go."],
  ['structure', "Give each section a different answer to a question about {theme}, and let the structure disagree with itself before it settles."],

  // ── setting ─────────────────────────────────────────────────────────────────
  ['setting', "A seaside resort out of season, with shuttered rides, an empty promenade and a single open cafe that makes every conversation feel overheard."],
  ['setting', "A hospital at night, the one place where the whole town's strangers meet and everyone is a little more honest than they planned to be."],
  ['setting', "A border post where the queue moves slowly and the waiting room becomes its own small society, with its own rules, rivals and romances."],
  ['setting', "A tower block where the lift breaks and the whole building must learn, for the first time, to rely on the stairs and on each other."],
  ['setting', "A remote research station in the dark season, where supplies are rationed, the faces never change and every old grudge has room to grow."],
  ['setting', "A once-grand department store after closing, with mannequins, lifts that stop between floors and the unspoken territory of the night staff."],
  ['setting', "Let {place} be a character with moods: a season it loves, a time of day it dreads, and rooms people drift away from for reasons nobody can name."],
  ['setting', "A floating market, a night train or any place where the neighbours change every day and nobody stays long enough to be held accountable."],
  ['setting', "A small town whose only industry has just closed, and a single cafe where all the former rivals now meet because there is nowhere else."],
  ['setting', "A palace, school or monastery with a small staircase everyone is forbidden to use, and a whole social order that depends on pretending it is not there."],
  ['setting', "An island whose ferry runs only when the tide allows, so every arrival and departure must be planned around something nobody controls."],
  ['setting', "A city split by a river, a wall or a long-standing quarrel over a bridge, where the people on each bank have started to invent each other."],
  ['setting', "Add a door, a floor or an hour to {place} that people only ever mention sideways, and let it become what everyone's routine is quietly built around."],
  ['setting', "Picture {place} on its worst day of the year, when everyone who usually avoids each other is forced to be there together."],

  // ── title ───────────────────────────────────────────────────────────────────
  ['title', "Name it after an object the reader carries through the story without noticing, and let the last scene make the name suddenly heavy."],
  ['title', "Consider a title that is a question the story answers only at the very end, so the reader holds it in mind throughout."],
  ['title', "Take the title from a phrase one minor character says once, almost in passing, which the reader later realises was the truest thing anyone said."],
  ['title', "Choose a title that sounds like something else, a recipe, a legal term or a weather report, so the story gradually rewrites its meaning."],
  ['title', "Try naming the story for what is missing, the absent person, the unbuilt house or the unsent letter, so the reader starts looking for it from the very first glance."],
  ['title', "Consider a title drawn from how locals refer to {place}, so the name carries a history the reader will gradually learn."],
  ['title', "Pick a title that promises the wrong genre, a cosy name on a bleak story or a menacing name on a gentle one, and let the mismatch do some work."],
  ['title', "A one-word title that changes meaning as the story turns, starting as a place or a name and ending as a verdict."],
  ['title', "Title the story after the antagonist, or the thing everyone fears, and let the reader slowly wonder why the hero's name is not on the cover."],
  ['title', "A title that is a rule or a warning from the world of the story, the kind painted above a door, so the reader meets the law before the plot."],
  ['title', "A title built from two ordinary words that have never been paired, so they sit uneasily together and the story has to reconcile them."],
  ['title', "Look for a title in the smallest, most ordinary form of {theme}, an object or a habit, rather than the grand abstract word."],
  ['title', "Let the title be what {who} is called by one person only, and let the reader learn who that person is late in the story."],

  // ── motif ───────────────────────────────────────────────────────────────────
  ['motif', "A door that is always slightly open, then closed, then locked, then removed, tracing the relationships in the story without anyone remarking on it."],
  ['motif', "A recurring weather pattern that arrives a little before bad news, until the characters begin to treat rain as a polite warning."],
  ['motif', "Hands: who holds what, who lets go and who never touches anyone, tracked quietly through every scene."],
  ['motif', "A tune or whistle that moves from character to character, losing a few notes each time, until only the rhythm is left."],
  ['motif', "Mending: a coat patched, a roof fixed, a friendship stitched back together, repeated until the reader senses something very large being repaired in small ways."],
  ['motif', "An unfinished thing in every household, a half-knitted scarf, a half-painted wall, a half-read book, so the whole community feels like it is waiting for someone to come back and finish."],
  ['motif', "Water in different states, a leak, a flood, a frozen pond, a glass left untouched, following the emotional temperature of the story."],
  ['motif', "Mirrors and reflections that are slightly delayed or slightly wrong, scattered through the story until the reader senses a second version of {who} waiting."],
  ['motif', "A recurring meal that changes as relationships change: the same table, the same dish, and a different number of chairs."],
  ['motif', "Keys, locks and who is given a copy: let the passing of keys carry the story's trust more clearly than any conversation."],
  ['motif', "Let a character keep counting something compulsively, such as stairs, bells or missing spoons, and make the count come out wrong exactly once, at the moment the story turns."],
  ['motif', "Choose one sound in {place}, a creak, a bell or a hum, and let it be heard in every scene, then silenced at the moment the story turns."],
  ['motif', "Find a physical object that quietly stands for {theme} and let it be lost, found, given away and returned over the course of the story."],
  ['motif', "Give {who} a small recurring gesture that other characters begin to copy without realising."],

  // ── question ────────────────────────────────────────────────────────────────
  ['question', "What does {who} believe about themselves that the story is going to prove untrue, and who in the story already suspects it?"],
  ['question', "What is the smallest thing that could go wrong in the first scene, and how many later events could trace back to it?"],
  ['question', "Who benefits if the central problem is never solved, and how hard are they working to keep it that way?"],
  ['question', "What does the world of this story believe is impossible, and what happens in the scene where that belief is shown to be wrong?"],
  ['question', "If the story were told by the person who loses, what would they say it was about, and how different would that be from your version?"],
  ['question', "What is an ordinary day in {place} like before anything happens, and which part of that day will be missing by the end?"],
  ['question', "Which single choice made before the story begins is responsible for everything that follows, and does anyone know it was a choice?"],
  ['question', "What is the one thing the reader must know by the midpoint to feel the ending is fair, and where will you hide it in plain sight?"],
  ['question', "Who in this story is not allowed to be angry, and what does the anger do instead?"],
  ['question', "What does {who} do when no one is watching, and is any part of the story about the difference?"],
  ['question', "Is the central relationship one the reader wants to see survive, and if not, what would make them care?"],
  ['question', "Who in this story would argue hardest against {theme}, and are they entirely wrong?"],
  ['question', "What would {who} never forgive, and what is the first moment in the story that forces them to?"],
];
