// Idea bank: world. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
// Strings use double quotes so apostrophes read naturally; the text itself never contains quotation marks.
export default [
  // ── spark ───────────────────────────────────────────────────────────────────
  ['spark', "A city built on the back of something enormous and asleep, where the oldest building rule is simply never to make it itch."],
  ['spark', "A world where every doorway remembers the last person through it, and a house is priced by how gracefully its former tenants left."],
  ['spark', "Sleep is a public utility in this society: dreams are metered, lent between neighbours and, in hard winters, overdrawn."],
  ['spark', "In a country where the dead remain citizens, voting, paying taxes and holding grudges through appointed living proxies, the proxies have begun to develop opinions of their own."],
  ['spark', "A boarding house that rearranges its own corridors each winter, and a tenants' etiquette so elaborate it has become the local legal system."],
  ['spark', "A country with no capital, only a travelling court that spends a season in each town, so every town's economy is built on the memory and the hope of being hosted."],
  ['spark', "There is a village where one hour of every day goes unclaimed, and by long agreement everyone stays indoors and says nothing until it passes."],
  ['spark', "{Place} has a seam, a spot where the rules of everything else quietly stop applying, and the locals have furnished carefully around it."],
  ['spark', "If {theme} were the local weather, everyone would own the right coat for it and argue about the forecast at breakfast."],
  ['spark', "A world that has spent generations preparing for {who}'s greatest mistake, with holidays, laws and a whole insurance trade built around its arrival."],
  ['spark', "In {place}, everyone's name is also a job title, and {who} is the only person whose title nobody can explain."],

  // ── rule ────────────────────────────────────────────────────────────────────
  ['rule', "Weather answers to the largest crowd beneath it, so public gatherings are licensed like weapons and nobody can organise a picnic without becoming briefly political."],
  ['rule', "Every lie leaves a faint scent in the room, so diplomats choose their cologne as carefully as their words, and the truly honest are known by smelling of nothing."],
  ['rule', "Debts are physical here: the more you owe someone, the harder you are pulled toward them, and great creditors walk surrounded by an orbit of the desperate."],
  ['rule', "The machines work wonderfully, but only while someone nearby sincerely believes in them, so every factory employs a team of professional optimists."],
  ['rule', "The dead may be consulted exactly once, and only by someone they disliked in life, which turns every inheritance dispute into a delicate diplomatic mission."],
  ['rule', "A ruler's authority ends precisely where their voice can no longer be heard, so every empire is an exercise in amplification and silence is the only true frontier."],
  ['rule', "Illness can be moved to a willing person but never destroyed, so there is a quiet economy of volunteers and a standing argument about what counts as willing."],
  ['rule', "Nothing agreed over food is binding until the plates are cleared, so diplomacy has become a contest of who can keep a meal going longest."],
  ['rule', "In {place}, nothing can be thrown away, only passed on, and the whole social order depends on who is obliged to accept the next unwanted thing."],
  ['rule', "The rule everyone here obeys without being able to name is the one {who} keeps breaking by accident."],
  ['rule', "A memory survives only while two living people share it, so the last witness to anything forgets fast and every close friendship doubles as a filing system."],
  ['rule', "Places that nobody visits slowly drift out of reach, so every road is held in place by traffic, and a remote village survives by staying a little too interesting to ignore."],

  // ── culture ─────────────────────────────────────────────────────────────────
  ['culture', "An apology is measured by how inconvenient the gift is, so carrying something heavy or fragile across town is the most sincere thing a person can do."],
  ['culture', "Goodbyes are honoured far above greetings, with elaborate departure rites, while anyone who simply arrives is met with polite embarrassment."],
  ['culture', "Funerals are held long after the death, on purpose, because grief is thought to belong to the time when everyone else has stopped bringing food."],
  ['culture', "Everyone is issued a handful of tokens, each able to cancel one insult, and a person's standing is measured by how many they still hold unspent."],
  ['culture', "A people who believe their god to be painfully shy worship by looking pointedly elsewhere, and the devout are known by how carefully they avoid the sky."],
  ['culture', "Hospitality is absolute here, so feuds are fought by arranging who is currently whose guest, and an invitation can be an act of war."],
  ['culture', "Adulthood arrives when a person has kept something alive for a full year, whether a plant, a fire or a rumour, and the choice says everything about them."],
  ['culture', "On a ship that will outlast everyone aboard, nobody marks birthdays; families keep the day their ancestors boarded instead, and squabbling over whose boarding came first has become a form of rank."],
  ['culture', "The yearly ritual is a public performance of {theme}, and the real politics lies in who is cast and who is quietly left out."],
  ['culture', "In {place}, it is deeply rude to ask what someone does for a living and perfectly polite to ask what they are currently afraid of."],
  ['culture', "{Who} follows a custom from home that nobody around them has a word for, and the people who notice keep mistaking it for rudeness."],
  ['culture', "Mourners in {place} take over the dead person's most hated chore for a season, and you can judge how loved someone was by the state of their gutters."],
  ['culture', "The local language has a grammatical mood reserved for things that are true only because someone important said so, and children learn to hear it before they learn to count."],

  // ── place ───────────────────────────────────────────────────────────────────
  ['place', "Whole neighbourhoods have grown along a bridge so long that the two banks still argue about who owns the middle."],
  ['place', "A library whose books are shelved by how badly each was once wanted, so the most coveted sit in the dark at the back and the unloved crowd the door."],
  ['place', "A harbour whose sea left in one night, where the fleet is still moored, the customs house is still open and the harbour master still collects fees."],
  ['place', "A town built along a single street that never seems to end, where addresses are given in distance walked, and the two ends are rumoured to be neighbours."],
  ['place', "A town linked to the mainland by a causeway the sea covers twice a day, so its law, courtship and trade all run on the tide table and stranded visitors are its main industry."],
  ['place', "A space station slowly overgrown by its own hydroponic gardens, where the corridors that still exist are the ones the plants have decided to allow."],
  ['place', "There is a neighbourhood that exists only after dusk; by day it is a blank wall and a rumour, and its residents have learned to make a living from being nowhere."],
  ['place', "Two kingdoms own the same mountain pass on alternating days, so every traveller carries two sets of papers and the toll keeper is the only reliable calendar."],
  ['place', "Beneath {place} lies a second version of it, quieter and a little older, and the residents of each keep up a polite pretence that they have never visited."],
  ['place', "The one place where {who} could be completely alone is also the most carefully watched corner of the map, and the watchers are famously discreet."],
  ['place', "A city whose layout is a quiet argument about {theme}, with its streets, squares and dead ends each taking a different side."],
  ['place', "Every road out of {place} bends gently back toward it, and there is a settled etiquette for the rare person who truly gets away."],
  ['place', "A marketplace with no stalls and no goods, only people who know where things can be found, so the whole economy runs on being correctly introduced."],

  // ── history ─────────────────────────────────────────────────────────────────
  ['history', "A war ended so long ago that both sides now insist they lost it, because the defeated were guaranteed the better pensions."],
  ['history', "A famous queen who may never have existed, and a thriving trade in rival tombs, relics and descendants that would collapse if anyone proved it either way."],
  ['history', "The empire fell not to conquest but because its last administrators simply stopped answering letters, and the provinces gradually realised that nobody was in charge."],
  ['history', "The great flood was an engineering failure, but the national story requires it to be divine, and a long line of engineers has kept the silence."],
  ['history', "The golden age owes its glow to a successor government that burned the dull records, and the dull records are exactly what a curious historian wants now."],
  ['history', "The history of a family home is told through a single piece of furniture that every generation has repaired, renamed and quarrelled over, until nobody agrees what it was for."],
  ['history', "One early invention was suppressed, and every later technology in this world is a clumsy detour around that single banned idea."],
  ['history', "Colonists arrived to find the planet already carefully tidied, and the first generation's entire mythology is an attempt to account for the previous tenants."],
  ['history', "{Place} sits on layers of earlier settlements, each leaving the next a warning, and the people on top have only just lost the habit of reading them."],
  ['history', "{Who}'s family once owned the one thing this world now argues over, and how they lost it is still the favourite local story, told differently in every district."],
  ['history', "The real cause of the great war was {theme}, and the official explanation survives only because it is easier to live with."],
  ['history', "The oldest surviving document in {place} is a formal complaint, and the culture that grew up around it still treats grievance as a founding virtue."],
  ['history', "The last calendar reform was abandoned halfway, so the world runs on two calendars at once, and anyone born in the gap between them legally belongs to neither."],

  // ── tension ─────────────────────────────────────────────────────────────────
  ['tension', "Two guilds depend on each other completely and have spent generations pretending otherwise, so neither dares do anything that might reveal how fast each would collapse alone."],
  ['tension', "The wall around the old quarter is revered by one faction as protection and by another as a cage, and in private both are paying to keep it repaired."],
  ['tension', "Elders who lived through the shortage now waste food in open defiance, while the young, raised on stories of hunger, hoard salt and cannot forgive them."],
  ['tension', "Priests bless the water and engineers purify it, and each side privately fears that the other's contribution is the one doing the real work."],
  ['tension', "The district's leases all fall due on a single day set by an absent landlord, so neighbours who barely speak form factions over who should negotiate."],
  ['tension', "Both sides of the feud would end it tomorrow if neither had to be the one who blinked, and a whole industry of go-betweens lives off that standoff."],
  ['tension', "A fragile peace rests on a hostage exchange that has run so long the hostages have married, raised children and begun voting in each other's cities."],
  ['tension', "The merchants' road is kept up by a company that has never raised its fee and has lately begun to mention, mildly, what it might one day want in return."],
  ['tension', "Everyone in {place} knows which family really runs things, and that family's whole strategy is to look as though it does not."],
  ['tension', "{Who} belongs, by birth, to a faction that both sides of the central dispute would like to claim and neither fully trusts."],
  ['tension', "The political fault line of this world is, underneath, an argument about {theme}, though every faction would insist it is about land, taxes or old insults."],
  ['tension', "A canal that would enrich the lower valley and flood the upper one has been approved by a council whose members live in neither."],

  // ── texture ─────────────────────────────────────────────────────────────────
  ['texture', "Each street has its own smell that residents navigate by, and moving house is a kind of bereavement because you must learn to smell your way home again."],
  ['texture', "Loaves are shaped to their household's craft, and an unmarked loaf on the table is how a family announces a change it has not yet told the neighbours."],
  ['texture', "Pockets are treated as intimate territory, so lending a coat is a declaration, and tailors, who know exactly what everyone carries, are trusted like confessors."],
  ['texture', "Houses lean almost imperceptibly toward the neighbours their families like, so a visitor can read a street's alliances from the tilt of its chimneys."],
  ['texture', "A permanent low note from the machinery under the city is so familiar that its rare silences are felt as emergencies."],
  ['texture', "One small window in each home is left unwashed on purpose, and the grime that builds up there serves as the household's unofficial record of its years."],
  ['texture', "Public screens display an ambient mood for the whole district, and living under a bad one is treated like bad weather, with sympathy cards and borrowed umbrellas."],
  ['texture', "Every household has its own whistle for calling its people home, and a stranger who copies one is taken to be making either a joke or a proposal."],
  ['texture', "In {place}, every sign hangs at the height of a child's eyes, for a reason that has outlived its explanation, and strangers spend their first week stooping."],
  ['texture', "The everyday details {who} has stopped noticing, such as the taste of the water and the way strangers stand, are the very ones a newcomer would find strangest."],
  ['texture', "Everyday life here carries the flavour of {theme} in its smallest habits, from how people knock on doors to how they leave a table."],
  ['texture', "A fine dust settles on everything each morning, and a whole etiquette has grown up around it, from brushes at every threshold to the unspoken ranking of whose steps are swept first."],

  // ── secret ──────────────────────────────────────────────────────────────────
  ['secret', "The city's famous clock has not kept true time for generations, and an elderly keeper nudges shop hours and ferry schedules to cover for it so nobody notices."],
  ['secret', "The oath recited at every coronation is a mistranslation introduced long ago by a clerk with a grudge, and the original wording would be far more dangerous to hear."],
  ['secret', "Every official map omits one street, and the guild that does it has long forgotten why, knowing only that the penalty for adding it back was never repealed."],
  ['secret', "The famed night watch was disbanded long ago, and the streets stay safe because a scattering of insomniacs each believe they are doing it alone."],
  ['secret', "The land's guardian spirits are not fighting off the dangers at the edge; they are negotiating with them, and the price goes up every year."],
  ['secret', "The town's famously warm welcome to strangers has a reason nobody states aloud: the place is emptying, and every guest is silently being auditioned as a future neighbour."],
  ['secret', "The temple's miracles are genuine, and they are paid for by one person in the region who has been ageing faster since the first of them."],
  ['secret', "Nothing lies beyond the known ocean, and every returning expedition was sworn to report distant lands, because the truth was judged worse for morale than a lie."],
  ['secret', "A room that appears on no plan exists somewhere in {place}, and everyone who has been inside has become unnervingly generous toward whoever showed them."],
  ['secret', "Several of this world's most respectable institutions have been watching {who} since long before {who} knew to look, and every one of them has the same reason."],
  ['secret', "The founders sealed {theme} away on purpose, somewhere in the foundations of this world, and their descendants have maintained the seal ever since."],
  ['secret', "The thing {who} was always told to stay away from in {place} is not dangerous at all, merely embarrassing to the people who have kept up the warning."],

  // ── question ────────────────────────────────────────────────────────────────
  ['question', "What does everyone in this world fear running out of, and who has arranged to be holding the last of it?"],
  ['question', "What is the one thing everyone here agrees is priceless, and who has put a price on it anyway?"],
  ['question', "Who is allowed to break the rules here, and what does the rest of society do to make that exception bearable?"],
  ['question', "What does an unremarkable morning look like here, with no war, no crisis and no great event, and who would be bored by it?"],
  ['question', "How does news travel in this world, and who decides what arrives late, what arrives garbled and what never arrives at all?"],
  ['question', "What is the oldest unresolved argument in this world, and which group would suffer most if it were finally settled?"],
  ['question', "When someone here is dying, who do they most want in the room, and what does that reveal about what the culture secretly values?"],
  ['question', "What does this world do with the people it has no use for, and what does it tell its children about them?"],
  ['question', "What would a stranger have to carry, learn or promise before being allowed to stay in {place} for a full season?"],
  ['question', "Which rule of this world does {who} privately think is wrong, and what would it cost {who} to say so aloud?"],
  ['question', "Which institution in this world exists because of {theme}, and which exists to hide it?"],
  ['question', "What does {place} look like to someone who has never left it, and what would they find missing the first time they travelled?"],
  ['question', "Where does this world's wealth actually come from, and who lives closest to the source without sharing in it?"],
  ['question', "What is the most embarrassing thing a person can be good at in this world?"],
];
