// Idea bank: world. Tuples of [lens, template]. See tests/brainstorm-banks.test.js for the rules.
// Strings use double quotes so apostrophes read naturally; the text itself never contains quotation marks.
export default [
  // ── spark ───────────────────────────────────────────────────────────────────
  ['spark', "A city built on the back of something enormous and asleep, where the oldest building rule is simply never to make it itch."],
  ['spark', "A world where every doorway remembers the last person through it, and a house is priced by how gracefully its former tenants left."],
  ['spark', "A society that treats sleep as a public utility: dreams are metered, lent between neighbours and, in bad winters, quietly overdrawn."],
  ['spark', "In a country where the dead remain citizens, voting, paying taxes and holding grudges through appointed living proxies, the proxies have begun to develop opinions of their own."],
  ['spark', "A boarding house that rearranges its own corridors each winter, and a tenants' etiquette so elaborate it has become the local legal system."],
  ['spark', "A realm where every promise carries a physical weight until it is kept, so honest people travel light and politicians walk with a permanent stoop."],
  ['spark', "A village where one hour of the day is simply unclaimed, and by long agreement everyone stays indoors and says nothing until it passes."],
  ['spark', "{Place} has a seam, a spot where the rules of everything else quietly stop applying, and the locals have furnished carefully around it."],
  ['spark', "If {theme} were the local weather, everyone would own the right coat for it and argue about the forecast at breakfast."],
  ['spark', "A world that has spent generations preparing for {who}'s greatest mistake, with holidays, laws and a whole insurance trade built around its arrival."],
  ['spark', "In {place}, everyone's name is also a job title, and {who} is the only person whose title nobody can explain."],

  // ── rule ────────────────────────────────────────────────────────────────────
  ['rule', "Anything can be enchanted, but only with something the enchanter would truly miss, so the strongest spells belong to the people with the most to lose."],
  ['rule', "Every lie leaves a faint scent in the room, so diplomats choose their cologne as carefully as their words, and the truly honest are known by smelling of nothing."],
  ['rule', "Debts are physical here: the more you owe someone, the harder you are pulled toward them, and great creditors walk surrounded by an orbit of the desperate."],
  ['rule', "The machines work wonderfully, but only while someone nearby sincerely believes in them, so every factory employs a team of professional optimists."],
  ['rule', "The dead may be consulted exactly once, and only by someone they disliked in life, which turns every inheritance dispute into a delicate diplomatic mission."],
  ['rule', "A ruler's authority ends precisely where their voice can no longer be heard, so every empire is an exercise in amplification and silence is the only true frontier."],
  ['rule', "Illness can be moved to a willing person but never destroyed, so there is a quiet economy of volunteers and a standing argument about what counts as willing."],
  ['rule', "Nothing agreed over food is binding until the plates are cleared, so diplomacy has become a contest of who can keep a meal going longest."],
  ['rule', "In {place}, nothing can be thrown away, only passed on, and the whole social order depends on who is obliged to accept the next unwanted thing."],
  ['rule', "The rules here are tightening, one exception at a time, and {who} is the first to notice that the exceptions were holding everything up."],
  ['rule', "Every act of kindness in {place} is remembered by the walls and eventually repaid, and the authorities cannot decide whether that is a blessing or a tax."],

  // ── culture ─────────────────────────────────────────────────────────────────
  ['culture', "An apology is measured by how inconvenient the gift is, so carrying something heavy or fragile across town is the most sincere thing a person can do."],
  ['culture', "Goodbyes are honoured far above greetings, with elaborate departure rites, while anyone who simply arrives is met with polite embarrassment."],
  ['culture', "Funerals are held long after the death, on purpose, because the culture holds that grief belongs to the time when everyone else has stopped bringing food."],
  ['culture', "Everyone carries a small token that can be spent once to cancel an insult, and a person's standing is measured by how many they have never needed."],
  ['culture', "Their god is thought to be profoundly shy, so worship consists of looking pointedly elsewhere, and the devout are recognised by how studiously they avoid the sky."],
  ['culture', "Hospitality is absolute: a host must protect a guest from everything except the host's own family, so feuds are settled by cleverly arranging who is currently whose guest."],
  ['culture', "Adulthood arrives when a person has kept something alive for a full year, whether a plant, a fire or a rumour, and the choice says everything about them."],
  ['culture', "On the long-haul ship, families celebrate the anniversary of their boarding rather than anyone's birth, so belonging is counted in generations instead of years."],
  ['culture', "The great yearly ritual is a public performance of {theme}, and the real politics lies in who is cast and who is quietly left out."],
  ['culture', "In {place}, it is deeply rude to ask what someone does for a living and perfectly polite to ask what they are currently afraid of."],
  ['culture', "{Who} grew up with a custom that outsiders find shocking and insiders find so ordinary that explaining it takes a whole evening."],
  ['culture', "Mourners in {place} take over the dead person's most hated chore for a season, and you can judge how loved someone was by the state of their gutters."],

  // ── place ───────────────────────────────────────────────────────────────────
  ['place', "A bridge so long that whole neighbourhoods have grown along it, and the two banks still argue about who owns the middle."],
  ['place', "A library whose books are shelved by how badly each was once wanted, so the most coveted sit in the dark at the back and the unloved crowd the door."],
  ['place', "A harbour whose sea left in one night, where the fleet is still moored, the customs house is still open and the harbour master still collects fees."],
  ['place', "A town built along a single street that never seems to end, where addresses are given in distance walked, and the two ends are rumoured to be neighbours."],
  ['place', "A family house whose kitchen is the only neutral ground, where every feud pauses at the threshold and the oven is the nearest thing to a judge."],
  ['place', "A space station slowly overgrown by its own hydroponic gardens, where the corridors that still exist are the ones the plants have decided to allow."],
  ['place', "A neighbourhood that is only there after dusk; by day it is a blank wall and a rumour, and its residents have learned to make a living from being nowhere."],
  ['place', "A mountain pass that belongs to two kingdoms on alternating days, so every traveller carries two sets of papers and the toll keeper is the only reliable calendar."],
  ['place', "Beneath {place} lies a second version of it, quieter and a little older, and the residents of each keep up a polite pretence that they have never visited."],
  ['place', "Somewhere there is a spot where {who} could be truly alone, and it is the most closely watched corner of the map, watched by people with a long tradition of discretion."],
  ['place', "A city whose layout is a quiet argument about {theme}, with its streets, squares and dead ends each taking a different side."],
  ['place', "Every road out of {place} bends gently back toward it, and there is a quiet etiquette for the rare person who truly gets away."],

  // ── history ─────────────────────────────────────────────────────────────────
  ['history', "A war ended so long ago that both sides now insist they lost it, because the defeated were guaranteed the better pensions."],
  ['history', "A famous queen who may never have existed, and a thriving trade in rival tombs, relics and descendants that would collapse if anyone proved it either way."],
  ['history', "The empire fell not to conquest but because its last administrators quietly stopped answering letters, and the provinces gradually realised that nobody was in charge."],
  ['history', "The great flood was an engineering failure, but the national story requires it to be divine, and a long line of engineers has kept the silence."],
  ['history', "The golden age owes its glow to a successor government that burned the dull records, and the dull records are exactly what a curious historian wants now."],
  ['history', "The history of a family home is told through a single piece of furniture that every generation has repaired, renamed and quarrelled over, until nobody agrees what it was for."],
  ['history', "One early invention was suppressed, and every later technology in this world is a clumsy detour around that single banned idea."],
  ['history', "Colonists arrived to find the planet already carefully tidied, and the first generation's entire mythology is an attempt to account for the previous tenants."],
  ['history', "{Place} sits on layers of earlier settlements, each leaving the next a warning, and the topmost layer has only just lost the habit of reading them."],
  ['history', "The founding story includes an unflattering cameo by {who}'s family, and every institution in the world has an interest in keeping it that way."],
  ['history', "{Theme} was the real cause of the great war, and the official explanation survives only because it is easier to forgive."],
  ['history', "The oldest surviving document in {place} is a formal complaint, and the culture that grew up around it still treats grievance as a founding virtue."],

  // ── tension ─────────────────────────────────────────────────────────────────
  ['tension', "Two guilds depend on each other completely and have spent generations pretending otherwise, so neither dares do anything that might reveal how fast each would collapse alone."],
  ['tension', "The border wall is revered by one faction as protection and by another as a cage, and in private both are quietly paying to extend it."],
  ['tension', "A generation raised after the shortage has never trusted abundance, and their elders, who remember hunger, cannot bear to watch them hoard stale bread in a time of plenty."],
  ['tension', "Priests bless the water and engineers purify it, and each side privately fears that the other's contribution is the one doing the real work."],
  ['tension', "Every lease in the district falls due on a single day set by an absent landlord, and neighbours who barely spoke are suddenly forming factions about who should negotiate."],
  ['tension', "Both sides of the feud would end it tomorrow if neither had to be the one who blinked, and a whole industry of go-betweens lives off that standoff."],
  ['tension', "A fragile peace rests on a hostage exchange that has run so long the hostages have married, raised children and begun voting in each other's cities."],
  ['tension', "The merchants' road is kept up by a company that has never raised its fee and has lately begun to mention, mildly, what it might one day want in return."],
  ['tension', "Everyone in {place} knows which district really runs things, and that district's whole strategy is to look as though it does not."],
  ['tension', "{Who} belongs, by birth, to a faction that both sides of the great quarrel would like to claim and neither fully trusts."],
  ['tension', "The political fault line of this world is, underneath, an argument about {theme}, though every faction would insist it is about land, taxes or old insults."],
  ['tension', "Half of {place} would welcome an outside judge to settle the old quarrel, and the other half is quietly arranging for none ever to arrive."],

  // ── texture ─────────────────────────────────────────────────────────────────
  ['texture', "Every street has its own smell that residents navigate by, and moving house is a kind of bereavement because you must learn to smell your way home again."],
  ['texture', "Loaves are shaped to their household's craft, and an unmarked loaf on the table is how a family announces a change it has not yet told the neighbours."],
  ['texture', "The staple soup tastes of whatever the cook was feeling when it was made, so nobody cooks while angry and a bland meal at home is a worrying sign."],
  ['texture', "Houses lean almost imperceptibly toward the neighbours their families like, so a visitor can read a street's alliances from the tilt of its chimneys."],
  ['texture', "A permanent low note from the machinery under the city is so familiar that its rare silences are felt as emergencies."],
  ['texture', "Every house keeps one small window that is never washed, and the grime that builds up there serves as the household's quiet, unofficial record of its years."],
  ['texture', "Public screens display an ambient mood for the whole district, and living under a bad one is treated like bad weather, with sympathy cards and borrowed umbrellas."],
  ['texture', "Every family on the block keeps one chair nobody sits in, and knowing whose chair it is and why is the real neighbourhood directory."],
  ['texture', "The first thing a visitor to {place} notices is a sound that residents have stopped hearing, and the second is that they stopped on purpose."],
  ['texture', "The everyday details {who} has stopped noticing, such as the taste of the water and the way strangers stand, are the very ones a newcomer would find strangest."],
  ['texture', "Everyday life here carries the flavour of {theme} in its smallest habits, from how people knock on doors to how they leave a table."],
  ['texture', "At a certain hour of the evening in {place}, everyone briefly stops what they are doing for a reason none of them can quite explain."],

  // ── secret ──────────────────────────────────────────────────────────────────
  ['secret', "The city's famous clock has not kept true time for generations, and an elderly keeper quietly nudges shop hours and ferry schedules so nobody notices."],
  ['secret', "The oath recited at every coronation is a mistranslation introduced long ago by a clerk with a grudge, and the original wording would be far more dangerous to hear."],
  ['secret', "Every official map omits one street, and the guild that does it has long forgotten why, knowing only that the penalty for adding it back was never repealed."],
  ['secret', "The founder's great sacrifice never happened; a committee of survivors invented it to give a frightened people something to be proud of, and they signed nothing."],
  ['secret', "The land's guardian spirits are not fighting off the dangers at the edge; they are negotiating with them, and the price goes up every year."],
  ['secret', "Every house on the street shares one hidden cellar, dug through by accident when the foundations were laid, and a few residents have used it for generations without telling the rest."],
  ['secret', "The temple's miracles are genuine, and they are paid for by one person in the region who has been ageing faster since the first of them."],
  ['secret', "Nothing lies beyond the known ocean, and every returning expedition was sworn to report distant lands, because the truth was judged worse for morale than a lie."],
  ['secret', "{Place} has a room that appears on no plan, and everyone who has been inside has become quietly, unnervingly generous toward the person who showed them."],
  ['secret', "Several of the world's most respectable institutions have been watching {who} since long before they arrived, and all of them have the same reason."],
  ['secret', "Somewhere in the world's foundations, {theme} was sealed away on purpose, and the founders' descendants have been maintaining the seal ever since."],
  ['secret', "The thing {who} was always told to stay away from in {place} is not dangerous at all, merely embarrassing to the people who have kept up the warning."],

  // ── question ────────────────────────────────────────────────────────────────
  ['question', "What does everyone in this world fear running out of, and who has quietly arranged to be holding the last of it?"],
  ['question', "If the rules of this world have a cost, who pays it, and do they know they are paying?"],
  ['question', "Who is allowed to break the rules here, and what does the rest of society do to make that exception bearable?"],
  ['question', "What does an unremarkable morning look like here, with no war, no magic and no quest, and who would be bored by it?"],
  ['question', "How does news travel in this world, and who decides what arrives late, what arrives garbled and what never arrives at all?"],
  ['question', "What is the oldest unresolved argument in this world, and which group would suffer most if it were finally settled?"],
  ['question', "When someone here is dying, who do they most want in the room, and what does that reveal about what the culture secretly values?"],
  ['question', "What does this world do with the people it has no use for, and what does it tell its children about them?"],
  ['question', "What would a stranger have to carry, learn or promise before being allowed to stay in {place} for a full season?"],
  ['question', "Which of this world's rules does {who} privately think is wrong, and what would it cost them to say so out loud?"],
  ['question', "Which institution in this world exists because of {theme}, and which exists to hide it?"],
  ['question', "What does {place} look like to someone who has never left it, and what would they find missing the first time they travelled?"],
];
